// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file multichain/wire/agent/v1/claim.proto (package multichain.wire.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { PolicyVerdict } from "./policy_pb.js";
import { file_multichain_wire_agent_v1_policy } from "./policy_pb.js";
import type { NumberRef, ProvenanceRef } from "../../shared/v1/provenance_pb.js";
import { file_multichain_wire_shared_v1_provenance } from "../../shared/v1/provenance_pb.js";
import type { SubgraphSlice } from "../../shared/v1/subgraph_pb.js";
import { file_multichain_wire_shared_v1_subgraph } from "../../shared/v1/subgraph_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/agent/v1/claim.proto.
 */
export const file_multichain_wire_agent_v1_claim: GenFile = /*@__PURE__*/
  fileDesc("CiRtdWx0aWNoYWluL3dpcmUvYWdlbnQvdjEvY2xhaW0ucHJvdG8SGG11bHRpY2hhaW4ud2lyZS5hZ2VudC52MSLuAwoFQ2xhaW0SCgoCaWQYASABKAkSEgoKc2Vzc2lvbl9pZBgCIAEoCRIxCgRraW5kGAMgASgOMiMubXVsdGljaGFpbi53aXJlLmFnZW50LnYxLkNsYWltS2luZBIQCghoZWFkbGluZRgEIAEoCRIVCg1ib2R5X21hcmtkb3duGAUgASgJEjwKCnByb3ZlbmFuY2UYBiADKAsyKC5tdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxLlByb3ZlbmFuY2VSZWYSPQoPc3VwcG9ydF9udW1iZXJzGAcgAygLMiQubXVsdGljaGFpbi53aXJlLnNoYXJlZC52MS5OdW1iZXJSZWYSRQoOc3ViZ3JhcGhfc2xpY2UYCCABKAsyKC5tdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxLlN1YmdyYXBoU2xpY2VIAIgBARI/Cg5wb2xpY3lfdmVyZGljdBgJIAEoCzInLm11bHRpY2hhaW4ud2lyZS5hZ2VudC52MS5Qb2xpY3lWZXJkaWN0EjoKDHN0dWJzX2FjdGl2ZRgKIAMoCzIkLm11bHRpY2hhaW4ud2lyZS5hZ2VudC52MS5TdHViTWFya2VyEhUKDWVtaXR0ZWRfYXRfbXMYCyABKA1CEQoPX3N1YmdyYXBoX3NsaWNlIkQKClN0dWJNYXJrZXISDAoEbmFtZRgBIAEoCRIOCgZyZWFzb24YAiABKAkSGAoQcHJvbW90ZWRfaW5fc2hpcBgDIAEoDSLDAgoORW1pdENsYWltSW5wdXQSMQoEa2luZBgBIAEoDjIjLm11bHRpY2hhaW4ud2lyZS5hZ2VudC52MS5DbGFpbUtpbmQSEAoIaGVhZGxpbmUYAiABKAkSFQoNYm9keV9tYXJrZG93bhgDIAEoCRI8Cgpwcm92ZW5hbmNlGAQgAygLMigubXVsdGljaGFpbi53aXJlLnNoYXJlZC52MS5Qcm92ZW5hbmNlUmVmEj0KD3N1cHBvcnRfbnVtYmVycxgFIAMoCzIkLm11bHRpY2hhaW4ud2lyZS5zaGFyZWQudjEuTnVtYmVyUmVmEkUKDnN1YmdyYXBoX3NsaWNlGAYgASgLMigubXVsdGljaGFpbi53aXJlLnNoYXJlZC52MS5TdWJncmFwaFNsaWNlSACIAQFCEQoPX3N1YmdyYXBoX3NsaWNlIjMKD0VtaXRDbGFpbU91dHB1dBIQCghjbGFpbV9pZBgBIAEoCRIOCgZwb2xpY3kYAiABKAkqoAEKCUNsYWltS2luZBIaChZDTEFJTV9LSU5EX1VOU1BFQ0lGSUVEEAASFgoSQ0xBSU1fS0lORF9QUk9GSUxFEAESFgoSQ0xBSU1fS0lORF9QQVRURVJOEAISGQoVQ0xBSU1fS0lORF9DT01QQVJJU09OEAMSFgoSQ0xBSU1fS0lORF9TVU1NQVJZEAQSFAoQQ0xBSU1fS0lORF9QVUxTRRAFYgZwcm90bzM", [file_multichain_wire_agent_v1_policy, file_multichain_wire_shared_v1_provenance, file_multichain_wire_shared_v1_subgraph]);

/**
 * Streamed analytical statement. The body uses ${ref:N} placeholders
 * the frontend replaces with interactive chips at render time.
 * `provenance[N]` is the typed entry the chip resolves against.
 *
 * @generated from message multichain.wire.agent.v1.Claim
 */
export type Claim = Message<"multichain.wire.agent.v1.Claim"> & {
  /**
   * ULID, sortable by emission order.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string session_id = 2;
   */
  sessionId: string;

  /**
   * @generated from field: multichain.wire.agent.v1.ClaimKind kind = 3;
   */
  kind: ClaimKind;

  /**
   * One-line plaintext headline.
   *
   * @generated from field: string headline = 4;
   */
  headline: string;

  /**
   * Structured paragraph; ${ref:N} placeholders -> provenance chips.
   *
   * @generated from field: string body_markdown = 5;
   */
  bodyMarkdown: string;

  /**
   * @generated from field: repeated multichain.wire.shared.v1.ProvenanceRef provenance = 6;
   */
  provenance: ProvenanceRef[];

  /**
   * @generated from field: repeated multichain.wire.shared.v1.NumberRef support_numbers = 7;
   */
  supportNumbers: NumberRef[];

  /**
   * None in v0; ship 5 populates for warehouse-derived historical.
   *
   * @generated from field: optional multichain.wire.shared.v1.SubgraphSlice subgraph_slice = 8;
   */
  subgraphSlice?: SubgraphSlice | undefined;

  /**
   * @generated from field: multichain.wire.agent.v1.PolicyVerdict policy_verdict = 9;
   */
  policyVerdict?: PolicyVerdict | undefined;

  /**
   * Stubs that touched this claim's emission. Visible in the UI as
   * "via stubs: ..." so historical claims keep their provenance even
   * after stubs are removed.
   *
   * @generated from field: repeated multichain.wire.agent.v1.StubMarker stubs_active = 10;
   */
  stubsActive: StubMarker[];

  /**
   * Wallclock ms since session started.
   *
   * @generated from field: uint32 emitted_at_ms = 11;
   */
  emittedAtMs: number;
};

/**
 * Describes the message multichain.wire.agent.v1.Claim.
 * Use `create(ClaimSchema)` to create a new message.
 */
export const ClaimSchema: GenMessage<Claim> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_claim, 0);

/**
 * Per-claim badge: which stubs short-circuited during this claim's
 * emission. Persists into history so stub provenance survives even
 * after the global registry is cleared.
 *
 * @generated from message multichain.wire.agent.v1.StubMarker
 */
export type StubMarker = Message<"multichain.wire.agent.v1.StubMarker"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;

  /**
   * @generated from field: uint32 promoted_in_ship = 3;
   */
  promotedInShip: number;
};

/**
 * Describes the message multichain.wire.agent.v1.StubMarker.
 * Use `create(StubMarkerSchema)` to create a new message.
 */
export const StubMarkerSchema: GenMessage<StubMarker> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_claim, 1);

/**
 * Input shape the model sends when calling `emit_claim`. Matches
 * Claim minus the runtime-stamped fields (id, session_id,
 * emitted_at_ms, policy_verdict, stubs_active are all controlled by
 * the runtime).
 *
 * @generated from message multichain.wire.agent.v1.EmitClaimInput
 */
export type EmitClaimInput = Message<"multichain.wire.agent.v1.EmitClaimInput"> & {
  /**
   * @generated from field: multichain.wire.agent.v1.ClaimKind kind = 1;
   */
  kind: ClaimKind;

  /**
   * @generated from field: string headline = 2;
   */
  headline: string;

  /**
   * @generated from field: string body_markdown = 3;
   */
  bodyMarkdown: string;

  /**
   * @generated from field: repeated multichain.wire.shared.v1.ProvenanceRef provenance = 4;
   */
  provenance: ProvenanceRef[];

  /**
   * @generated from field: repeated multichain.wire.shared.v1.NumberRef support_numbers = 5;
   */
  supportNumbers: NumberRef[];

  /**
   * @generated from field: optional multichain.wire.shared.v1.SubgraphSlice subgraph_slice = 6;
   */
  subgraphSlice?: SubgraphSlice | undefined;
};

/**
 * Describes the message multichain.wire.agent.v1.EmitClaimInput.
 * Use `create(EmitClaimInputSchema)` to create a new message.
 */
export const EmitClaimInputSchema: GenMessage<EmitClaimInput> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_claim, 2);

/**
 * Output of the `emit_claim` primitive. Returned to the model so it
 * knows the claim was committed.
 *
 * @generated from message multichain.wire.agent.v1.EmitClaimOutput
 */
export type EmitClaimOutput = Message<"multichain.wire.agent.v1.EmitClaimOutput"> & {
  /**
   * @generated from field: string claim_id = 1;
   */
  claimId: string;

  /**
   * String form of the verdict (e.g. "approved", "retracted").
   *
   * @generated from field: string policy = 2;
   */
  policy: string;
};

/**
 * Describes the message multichain.wire.agent.v1.EmitClaimOutput.
 * Use `create(EmitClaimOutputSchema)` to create a new message.
 */
export const EmitClaimOutputSchema: GenMessage<EmitClaimOutput> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_claim, 3);

/**
 * Closed enum: the renderer dispatches per-kind. v0 mostly emits
 * PROFILE; the rest are reserved for future ships so adding them
 * later doesn't require a wire change.
 *
 * Wire format: enum value name. PROFILE -> "PROFILE", etc.
 *
 * @generated from enum multichain.wire.agent.v1.ClaimKind
 */
export enum ClaimKind {
  /**
   * @generated from enum value: CLAIM_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CLAIM_KIND_PROFILE = 1;
   */
  PROFILE = 1,

  /**
   * @generated from enum value: CLAIM_KIND_PATTERN = 2;
   */
  PATTERN = 2,

  /**
   * @generated from enum value: CLAIM_KIND_COMPARISON = 3;
   */
  COMPARISON = 3,

  /**
   * @generated from enum value: CLAIM_KIND_SUMMARY = 4;
   */
  SUMMARY = 4,

  /**
   * @generated from enum value: CLAIM_KIND_PULSE = 5;
   */
  PULSE = 5,
}

/**
 * Describes the enum multichain.wire.agent.v1.ClaimKind.
 */
export const ClaimKindSchema: GenEnum<ClaimKind> = /*@__PURE__*/
  enumDesc(file_multichain_wire_agent_v1_claim, 0);

