// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file multichain/wire/agent/v1/constitution.proto (package multichain.wire.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/agent/v1/constitution.proto.
 */
export const file_multichain_wire_agent_v1_constitution: GenFile = /*@__PURE__*/
  fileDesc("CittdWx0aWNoYWluL3dpcmUvYWdlbnQvdjEvY29uc3RpdHV0aW9uLnByb3RvEhhtdWx0aWNoYWluLndpcmUuYWdlbnQudjEihwEKE0NvbnN0aXR1dGlvblZlcmRpY3QSDwoHdmVyZGljdBgBIAEoCRIOCgZyZWFzb24YAiABKAkSQAoKZXh0cmFjdGlvbhgDIAEoCzInLm11bHRpY2hhaW4ud2lyZS5hZ2VudC52MS5MbG1FeHRyYWN0aW9uSACIAQFCDQoLX2V4dHJhY3Rpb24inQEKDUxsbUV4dHJhY3Rpb24SRwoRbmFycmF0aXZlX251bWJlcnMYASADKAsyLC5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuTGxtRXh0cmFjdGVkTnVtYmVyEkMKDWNsYWltX251bWJlcnMYAiADKAsyLC5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuTGxtRXh0cmFjdGVkTnVtYmVyIkcKEkxsbUV4dHJhY3RlZE51bWJlchINCgV2YWx1ZRgBIAEoARISCgp1bml0X2NsYXNzGAIgASgJEg4KBnBocmFzZRgDIAEoCWIGcHJvdG8z");

/**
 * Constitution v3 response shape from the policy LLM. `verdict` is
 * one of three strings the policy prompt prescribes; `reason` defaults
 * to "" so a malformed older-style response still parses cleanly.
 * `extraction` is None when the LLM omitted the sidecar entirely.
 *
 * Note: this message is parsed leniently in Python (extra fields
 * ignored) because the policy LLM occasionally adds keys. The Rust
 * side serializes strictly.
 *
 * @generated from message multichain.wire.agent.v1.ConstitutionVerdict
 */
export type ConstitutionVerdict = Message<"multichain.wire.agent.v1.ConstitutionVerdict"> & {
  /**
   * One of: "approve", "retract", "reject".
   *
   * @generated from field: string verdict = 1;
   */
  verdict: string;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;

  /**
   * @generated from field: optional multichain.wire.agent.v1.LlmExtraction extraction = 3;
   */
  extraction?: LlmExtraction | undefined;
};

/**
 * Describes the message multichain.wire.agent.v1.ConstitutionVerdict.
 * Use `create(ConstitutionVerdictSchema)` to create a new message.
 */
export const ConstitutionVerdictSchema: GenMessage<ConstitutionVerdict> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_constitution, 0);

/**
 * Constitution gate's structured sidecar. Numbers the LLM saw in
 * narrative + claim text, classified by unit. The structural cross-
 * check pairs these against the binding store.
 *
 * @generated from message multichain.wire.agent.v1.LlmExtraction
 */
export type LlmExtraction = Message<"multichain.wire.agent.v1.LlmExtraction"> & {
  /**
   * @generated from field: repeated multichain.wire.agent.v1.LlmExtractedNumber narrative_numbers = 1;
   */
  narrativeNumbers: LlmExtractedNumber[];

  /**
   * @generated from field: repeated multichain.wire.agent.v1.LlmExtractedNumber claim_numbers = 2;
   */
  claimNumbers: LlmExtractedNumber[];
};

/**
 * Describes the message multichain.wire.agent.v1.LlmExtraction.
 * Use `create(LlmExtractionSchema)` to create a new message.
 */
export const LlmExtractionSchema: GenMessage<LlmExtraction> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_constitution, 1);

/**
 * LLM-side extracted number from constitution gate's `extraction`
 * JSON sidecar. `phrase` is debugging context only; surfaces in
 * dev-mode debug fields and is discarded during compare.
 *
 * @generated from message multichain.wire.agent.v1.LlmExtractedNumber
 */
export type LlmExtractedNumber = Message<"multichain.wire.agent.v1.LlmExtractedNumber"> & {
  /**
   * @generated from field: double value = 1;
   */
  value: number;

  /**
   * String form of UnitClass: "sol" | "count" | "community_id" | "raw".
   *
   * @generated from field: string unit_class = 2;
   */
  unitClass: string;

  /**
   * @generated from field: string phrase = 3;
   */
  phrase: string;
};

/**
 * Describes the message multichain.wire.agent.v1.LlmExtractedNumber.
 * Use `create(LlmExtractedNumberSchema)` to create a new message.
 */
export const LlmExtractedNumberSchema: GenMessage<LlmExtractedNumber> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_constitution, 2);

