// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file multichain/wire/agent/v1/diff.proto (package multichain.wire.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/agent/v1/diff.proto.
 */
export const file_multichain_wire_agent_v1_diff: GenFile = /*@__PURE__*/
  fileDesc("CiNtdWx0aWNoYWluL3dpcmUvYWdlbnQvdjEvZGlmZi5wcm90bxIYbXVsdGljaGFpbi53aXJlLmFnZW50LnYxIj0KCk5vTW92ZW1lbnQSEgoKcHJpb3JfdHVybhgBIAEoDRIbChNwcmltaXRpdmVzX3JlcGxheWVkGAIgAygJImEKDENoYW5nZWRTaW5jZRISCgpwcmlvcl90dXJuGAEgASgNEi4KBWRlbHRhGAIgASgLMh8ubXVsdGljaGFpbi53aXJlLmFnZW50LnYxLkRlbHRhEg0KBXByb3NlGAMgASgJIl0KBURlbHRhEjUKB2NoYW5nZWQYASADKAsyJC5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuRmllbGREZWx0YRIdChV1bmNoYW5nZWRfZmllbGRfY291bnQYAiABKA0iagoKRmllbGREZWx0YRISCgpmaWVsZF9wYXRoGAEgASgJEhEKCXByaW1pdGl2ZRgCIAEoCRI1CgZjaGFuZ2UYAyABKAsyJS5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuRmllbGRDaGFuZ2Ui9QEKC0ZpZWxkQ2hhbmdlEkgKDG51bWJlcl9tb3ZlZBgBIAEoCzIwLm11bHRpY2hhaW4ud2lyZS5hZ2VudC52MS5GaWVsZENoYW5nZU51bWJlck1vdmVkSAASRgoLc2V0X2NoYW5nZWQYAiABKAsyLy5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuRmllbGRDaGFuZ2VTZXRDaGFuZ2VkSAASSgoNY291bnRfY2hhbmdlZBgDIAEoCzIxLm11bHRpY2hhaW4ud2lyZS5hZ2VudC52MS5GaWVsZENoYW5nZUNvdW50Q2hhbmdlZEgAQggKBmNoYW5nZSJFChZGaWVsZENoYW5nZU51bWJlck1vdmVkEg0KBXByaW9yGAEgASgBEg8KB2N1cnJlbnQYAiABKAESCwoDcGN0GAMgASgBIjcKFUZpZWxkQ2hhbmdlU2V0Q2hhbmdlZBINCgVhZGRlZBgBIAMoCRIPCgdyZW1vdmVkGAIgAygJIjkKF0ZpZWxkQ2hhbmdlQ291bnRDaGFuZ2VkEg0KBXByaW9yGAEgASgBEg8KB2N1cnJlbnQYAiABKAFiBnByb3RvMw");

/**
 * Emitted when dont_repeat_yourself fires AND the diff is empty.
 * No LLM narrative call happens on this path; the bubble exists so
 * the user sees closure ("we covered this in turn N, no movement
 * since") rather than silence.
 *
 * @generated from message multichain.wire.agent.v1.NoMovement
 */
export type NoMovement = Message<"multichain.wire.agent.v1.NoMovement"> & {
  /**
   * @generated from field: uint32 prior_turn = 1;
   */
  priorTurn: number;

  /**
   * Primitive names re-fetched and confirmed unchanged.
   *
   * @generated from field: repeated string primitives_replayed = 2;
   */
  primitivesReplayed: string[];
};

/**
 * Describes the message multichain.wire.agent.v1.NoMovement.
 * Use `create(NoMovementSchema)` to create a new message.
 */
export const NoMovementSchema: GenMessage<NoMovement> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_diff, 0);

/**
 * Emitted when dont_repeat_yourself fires AND the diff is non-empty.
 * Carries the typed Delta plus the small narrative call's prose
 * describing only what shifted since the prior turn.
 *
 * @generated from message multichain.wire.agent.v1.ChangedSince
 */
export type ChangedSince = Message<"multichain.wire.agent.v1.ChangedSince"> & {
  /**
   * @generated from field: uint32 prior_turn = 1;
   */
  priorTurn: number;

  /**
   * @generated from field: multichain.wire.agent.v1.Delta delta = 2;
   */
  delta?: Delta | undefined;

  /**
   * @generated from field: string prose = 3;
   */
  prose: string;
};

/**
 * Describes the message multichain.wire.agent.v1.ChangedSince.
 * Use `create(ChangedSinceSchema)` to create a new message.
 */
export const ChangedSinceSchema: GenMessage<ChangedSince> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_diff, 1);

/**
 * Full diff result. unchanged_field_count powers the builder-view
 * chip ('2 changed / 4 unchanged'); only structurally-changed fields
 * appear in `changed`.
 *
 * @generated from message multichain.wire.agent.v1.Delta
 */
export type Delta = Message<"multichain.wire.agent.v1.Delta"> & {
  /**
   * @generated from field: repeated multichain.wire.agent.v1.FieldDelta changed = 1;
   */
  changed: FieldDelta[];

  /**
   * @generated from field: uint32 unchanged_field_count = 2;
   */
  unchangedFieldCount: number;
};

/**
 * Describes the message multichain.wire.agent.v1.Delta.
 * Use `create(DeltaSchema)` to create a new message.
 */
export const DeltaSchema: GenMessage<Delta> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_diff, 2);

/**
 * One field's change between prior turn's primitive output and the
 * freshly re-fetched output.
 *
 * @generated from message multichain.wire.agent.v1.FieldDelta
 */
export type FieldDelta = Message<"multichain.wire.agent.v1.FieldDelta"> & {
  /**
   * Dotted path within the primitive output (e.g.
   * "stats.in_volume_lamports").
   *
   * @generated from field: string field_path = 1;
   */
  fieldPath: string;

  /**
   * Producing primitive name (e.g. "wallet_profile").
   *
   * @generated from field: string primitive = 2;
   */
  primitive: string;

  /**
   * @generated from field: multichain.wire.agent.v1.FieldChange change = 3;
   */
  change?: FieldChange | undefined;
};

/**
 * Describes the message multichain.wire.agent.v1.FieldDelta.
 * Use `create(FieldDeltaSchema)` to create a new message.
 */
export const FieldDeltaSchema: GenMessage<FieldDelta> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_diff, 3);

/**
 * Shape of a single field's change. Three variants matching the
 * diff walker's FieldKind strategies (Number, EntitySet, Count).
 *
 * Wire format:
 *   numberMoved  -> {"numberMoved":  {"prior": 1, "current": 2, "pct": 1.0}}
 *   setChanged   -> {"setChanged":   {"added": [...], "removed": [...]}}
 *   countChanged -> {"countChanged": {"prior": 1, "current": 3}}
 *
 * @generated from message multichain.wire.agent.v1.FieldChange
 */
export type FieldChange = Message<"multichain.wire.agent.v1.FieldChange"> & {
  /**
   * @generated from oneof multichain.wire.agent.v1.FieldChange.change
   */
  change: {
    /**
     * @generated from field: multichain.wire.agent.v1.FieldChangeNumberMoved number_moved = 1;
     */
    value: FieldChangeNumberMoved;
    case: "numberMoved";
  } | {
    /**
     * @generated from field: multichain.wire.agent.v1.FieldChangeSetChanged set_changed = 2;
     */
    value: FieldChangeSetChanged;
    case: "setChanged";
  } | {
    /**
     * @generated from field: multichain.wire.agent.v1.FieldChangeCountChanged count_changed = 3;
     */
    value: FieldChangeCountChanged;
    case: "countChanged";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message multichain.wire.agent.v1.FieldChange.
 * Use `create(FieldChangeSchema)` to create a new message.
 */
export const FieldChangeSchema: GenMessage<FieldChange> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_diff, 4);

/**
 * Numeric field outside per-class tolerance. `pct` is the signed
 * percent change (current - prior) / prior, or 0.0 when prior is 0.
 *
 * @generated from message multichain.wire.agent.v1.FieldChangeNumberMoved
 */
export type FieldChangeNumberMoved = Message<"multichain.wire.agent.v1.FieldChangeNumberMoved"> & {
  /**
   * @generated from field: double prior = 1;
   */
  prior: number;

  /**
   * @generated from field: double current = 2;
   */
  current: number;

  /**
   * @generated from field: double pct = 3;
   */
  pct: number;
};

/**
 * Describes the message multichain.wire.agent.v1.FieldChangeNumberMoved.
 * Use `create(FieldChangeNumberMovedSchema)` to create a new message.
 */
export const FieldChangeNumberMovedSchema: GenMessage<FieldChangeNumberMoved> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_diff, 5);

/**
 * Entity-list field where membership changed. `added`/`removed`
 * carry the keys (typically wallet addresses).
 *
 * @generated from message multichain.wire.agent.v1.FieldChangeSetChanged
 */
export type FieldChangeSetChanged = Message<"multichain.wire.agent.v1.FieldChangeSetChanged"> & {
  /**
   * @generated from field: repeated string added = 1;
   */
  added: string[];

  /**
   * @generated from field: repeated string removed = 2;
   */
  removed: string[];
};

/**
 * Describes the message multichain.wire.agent.v1.FieldChangeSetChanged.
 * Use `create(FieldChangeSetChangedSchema)` to create a new message.
 */
export const FieldChangeSetChangedSchema: GenMessage<FieldChangeSetChanged> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_diff, 6);

/**
 * Count-class field where any delta is meaningful.
 *
 * @generated from message multichain.wire.agent.v1.FieldChangeCountChanged
 */
export type FieldChangeCountChanged = Message<"multichain.wire.agent.v1.FieldChangeCountChanged"> & {
  /**
   * @generated from field: double prior = 1;
   */
  prior: number;

  /**
   * @generated from field: double current = 2;
   */
  current: number;
};

/**
 * Describes the message multichain.wire.agent.v1.FieldChangeCountChanged.
 * Use `create(FieldChangeCountChangedSchema)` to create a new message.
 */
export const FieldChangeCountChangedSchema: GenMessage<FieldChangeCountChanged> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_diff, 7);

