// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file multichain/wire/agent/v1/entity.proto (package multichain.wire.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/agent/v1/entity.proto.
 */
export const file_multichain_wire_agent_v1_entity: GenFile = /*@__PURE__*/
  fileDesc("CiVtdWx0aWNoYWluL3dpcmUvYWdlbnQvdjEvZW50aXR5LnByb3RvEhhtdWx0aWNoYWluLndpcmUuYWdlbnQudjEizgEKCUVudGl0eVJlZhI7CgZ3YWxsZXQYASABKAsyKS5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuRW50aXR5UmVmV2FsbGV0SAASNwoEZWRnZRgCIAEoCzInLm11bHRpY2hhaW4ud2lyZS5hZ2VudC52MS5FbnRpdHlSZWZFZGdlSAASQQoJY29tbXVuaXR5GAMgASgLMiwubXVsdGljaGFpbi53aXJlLmFnZW50LnYxLkVudGl0eVJlZkNvbW11bml0eUgAQggKBmVudGl0eSIdCg9FbnRpdHlSZWZXYWxsZXQSCgoCaWQYASABKAkiGwoNRW50aXR5UmVmRWRnZRIKCgJpZBgBIAEoCSIgChJFbnRpdHlSZWZDb21tdW5pdHkSCgoCaWQYASABKA0iogEKC1ZpZXdDb250ZXh0EhgKEGxpdmVfd2luZG93X3NlY3MYASABKA0SNwoFZm9jdXMYAiABKAsyIy5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuRW50aXR5UmVmSACIAQESNgoJc2VsZWN0aW9uGAMgAygLMiMubXVsdGljaGFpbi53aXJlLmFnZW50LnYxLkVudGl0eVJlZkIICgZfZm9jdXNiBnByb3RvMw");

/**
 * Frontend ground-truth selection / focus. Distinct from
 * `shared.v1.ProvenanceRef` because EntityRef carries no analytics
 * metadata, just the entity identity.
 *
 * Wire format follows proto canonical JSON:
 *   wallet    -> {"wallet":    {"id": "<base58>"}}
 *   edge      -> {"edge":      {"id": "<edge_idx:gen>"}}
 *   community -> {"community": {"id": <u32>}}
 *
 * @generated from message multichain.wire.agent.v1.EntityRef
 */
export type EntityRef = Message<"multichain.wire.agent.v1.EntityRef"> & {
  /**
   * @generated from oneof multichain.wire.agent.v1.EntityRef.entity
   */
  entity: {
    /**
     * @generated from field: multichain.wire.agent.v1.EntityRefWallet wallet = 1;
     */
    value: EntityRefWallet;
    case: "wallet";
  } | {
    /**
     * @generated from field: multichain.wire.agent.v1.EntityRefEdge edge = 2;
     */
    value: EntityRefEdge;
    case: "edge";
  } | {
    /**
     * @generated from field: multichain.wire.agent.v1.EntityRefCommunity community = 3;
     */
    value: EntityRefCommunity;
    case: "community";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message multichain.wire.agent.v1.EntityRef.
 * Use `create(EntityRefSchema)` to create a new message.
 */
export const EntityRefSchema: GenMessage<EntityRef> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_entity, 0);

/**
 * @generated from message multichain.wire.agent.v1.EntityRefWallet
 */
export type EntityRefWallet = Message<"multichain.wire.agent.v1.EntityRefWallet"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message multichain.wire.agent.v1.EntityRefWallet.
 * Use `create(EntityRefWalletSchema)` to create a new message.
 */
export const EntityRefWalletSchema: GenMessage<EntityRefWallet> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_entity, 1);

/**
 * @generated from message multichain.wire.agent.v1.EntityRefEdge
 */
export type EntityRefEdge = Message<"multichain.wire.agent.v1.EntityRefEdge"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message multichain.wire.agent.v1.EntityRefEdge.
 * Use `create(EntityRefEdgeSchema)` to create a new message.
 */
export const EntityRefEdgeSchema: GenMessage<EntityRefEdge> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_entity, 2);

/**
 * @generated from message multichain.wire.agent.v1.EntityRefCommunity
 */
export type EntityRefCommunity = Message<"multichain.wire.agent.v1.EntityRefCommunity"> & {
  /**
   * @generated from field: uint32 id = 1;
   */
  id: number;
};

/**
 * Describes the message multichain.wire.agent.v1.EntityRefCommunity.
 * Use `create(EntityRefCommunitySchema)` to create a new message.
 */
export const EntityRefCommunitySchema: GenMessage<EntityRefCommunity> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_entity, 3);

/**
 * Structured ground-truth context the frontend builds from its own
 * DOM/state. Per D-6, the context block is the strongest disambiguation
 * signal; the prompt teaches the model to read it first.
 *
 * @generated from message multichain.wire.agent.v1.ViewContext
 */
export type ViewContext = Message<"multichain.wire.agent.v1.ViewContext"> & {
  /**
   * @generated from field: uint32 live_window_secs = 1;
   */
  liveWindowSecs: number;

  /**
   * None when the user hasn't focused any entity.
   *
   * @generated from field: optional multichain.wire.agent.v1.EntityRef focus = 2;
   */
  focus?: EntityRef | undefined;

  /**
   * @generated from field: repeated multichain.wire.agent.v1.EntityRef selection = 3;
   */
  selection: EntityRef[];
};

/**
 * Describes the message multichain.wire.agent.v1.ViewContext.
 * Use `create(ViewContextSchema)` to create a new message.
 */
export const ViewContextSchema: GenMessage<ViewContext> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_entity, 4);

