// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file multichain/wire/agent/v1/history.proto (package multichain.wire.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Claim } from "./claim_pb";
import { file_multichain_wire_agent_v1_claim } from "./claim_pb";
import type { AgentRuntime } from "./session_pb";
import { file_multichain_wire_agent_v1_session } from "./session_pb";
import type { ProvenanceRef } from "../../shared/v1/provenance_pb";
import { file_multichain_wire_shared_v1_provenance } from "../../shared/v1/provenance_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/agent/v1/history.proto.
 */
export const file_multichain_wire_agent_v1_history: GenFile = /*@__PURE__*/
  fileDesc("CiZtdWx0aWNoYWluL3dpcmUvYWdlbnQvdjEvaGlzdG9yeS5wcm90bxIYbXVsdGljaGFpbi53aXJlLmFnZW50LnYxIsMBCg1UaHJlYWRTdW1tYXJ5EhEKCXRocmVhZF9pZBgBIAEoCRI3CgdydW50aW1lGAIgASgOMiYubXVsdGljaGFpbi53aXJlLmFnZW50LnYxLkFnZW50UnVudGltZRIVCg1zdGFydGVkX2F0X21zGAMgASgEEhIKCnR1cm5fY291bnQYBCABKA0SDQoFdGl0bGUYBSABKAkSGgoSbGFzdF91c2VyX3F1ZXN0aW9uGAYgASgJEhAKCGFyY2hpdmVkGAcgASgIIkYKClRocmVhZExpc3QSOAoHdGhyZWFkcxgBIAMoCzInLm11bHRpY2hhaW4ud2lyZS5hZ2VudC52MS5UaHJlYWRTdW1tYXJ5IuoBCg5UcmFuc2NyaXB0VHVybhIMCgR0dXJuGAEgASgNEhUKDXVzZXJfcXVlc3Rpb24YAiABKAkSLwoGY2xhaW1zGAMgAygLMh8ubXVsdGljaGFpbi53aXJlLmFnZW50LnYxLkNsYWltEhYKDm5hcnJhdGl2ZV90ZXh0GAQgASgJEkYKFG5hcnJhdGl2ZV9wcm92ZW5hbmNlGAUgAygLMigubXVsdGljaGFpbi53aXJlLnNoYXJlZC52MS5Qcm92ZW5hbmNlUmVmEiIKGm5hcnJhdGl2ZV9yZXRyYWN0ZWRfcmVhc29uGAYgASgJIoQBChBUaHJlYWRUcmFuc2NyaXB0EjcKBnRocmVhZBgBIAEoCzInLm11bHRpY2hhaW4ud2lyZS5hZ2VudC52MS5UaHJlYWRTdW1tYXJ5EjcKBXR1cm5zGAIgAygLMigubXVsdGljaGFpbi53aXJlLmFnZW50LnYxLlRyYW5zY3JpcHRUdXJuYgZwcm90bzM", [file_multichain_wire_agent_v1_claim, file_multichain_wire_agent_v1_session, file_multichain_wire_shared_v1_provenance]);

/**
 * One row in the history list. Populated by reading the per-thread
 * `summary.json` sidecar (chunk 4); no full `state.json` read
 * required for the list view, so the endpoint stays cheap even at
 * a few thousand archived threads.
 *
 * `title` is the truncated first user_question (max ~80 chars);
 * `last_user_question` is the most recent question text the user
 * sent on this thread, used as the row's preview text. Both are
 * deterministic projections of state, not LLM-generated.
 *
 * @generated from message multichain.wire.agent.v1.ThreadSummary
 */
export type ThreadSummary = Message<"multichain.wire.agent.v1.ThreadSummary"> & {
  /**
   * @generated from field: string thread_id = 1;
   */
  threadId: string;

  /**
   * @generated from field: multichain.wire.agent.v1.AgentRuntime runtime = 2;
   */
  runtime: AgentRuntime;

  /**
   * @generated from field: uint64 started_at_ms = 3;
   */
  startedAtMs: bigint;

  /**
   * @generated from field: uint32 turn_count = 4;
   */
  turnCount: number;

  /**
   * @generated from field: string title = 5;
   */
  title: string;

  /**
   * @generated from field: string last_user_question = 6;
   */
  lastUserQuestion: string;

  /**
   * @generated from field: bool archived = 7;
   */
  archived: boolean;
};

/**
 * Describes the message multichain.wire.agent.v1.ThreadSummary.
 * Use `create(ThreadSummarySchema)` to create a new message.
 */
export const ThreadSummarySchema: GenMessage<ThreadSummary> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_history, 0);

/**
 * @generated from message multichain.wire.agent.v1.ThreadList
 */
export type ThreadList = Message<"multichain.wire.agent.v1.ThreadList"> & {
  /**
   * @generated from field: repeated multichain.wire.agent.v1.ThreadSummary threads = 1;
   */
  threads: ThreadSummary[];
};

/**
 * Describes the message multichain.wire.agent.v1.ThreadList.
 * Use `create(ThreadListSchema)` to create a new message.
 */
export const ThreadListSchema: GenMessage<ThreadList> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_history, 1);

/**
 * One turn re-projected for transcript playback when the user opens
 * a prior thread. Mirrors the SSE frame shapes the live path emits,
 * but flattened: claims + narrative + retraction reason all in one
 * place, no Done / Progress / GatePath noise (transcripts are
 * content-only, not the live event log).
 *
 * `narrative_text` is empty when the turn never produced prose
 * (e.g. boundary rejection or pre-chunk-4 thread missing the
 * `narratives_per_turn` field). The frontend renders no bubble in
 * that case.
 *
 * @generated from message multichain.wire.agent.v1.TranscriptTurn
 */
export type TranscriptTurn = Message<"multichain.wire.agent.v1.TranscriptTurn"> & {
  /**
   * @generated from field: uint32 turn = 1;
   */
  turn: number;

  /**
   * @generated from field: string user_question = 2;
   */
  userQuestion: string;

  /**
   * @generated from field: repeated multichain.wire.agent.v1.Claim claims = 3;
   */
  claims: Claim[];

  /**
   * @generated from field: string narrative_text = 4;
   */
  narrativeText: string;

  /**
   * @generated from field: repeated multichain.wire.shared.v1.ProvenanceRef narrative_provenance = 5;
   */
  narrativeProvenance: ProvenanceRef[];

  /**
   * empty = narrative was approved
   *
   * @generated from field: string narrative_retracted_reason = 6;
   */
  narrativeRetractedReason: string;
};

/**
 * Describes the message multichain.wire.agent.v1.TranscriptTurn.
 * Use `create(TranscriptTurnSchema)` to create a new message.
 */
export const TranscriptTurnSchema: GenMessage<TranscriptTurn> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_history, 2);

/**
 * @generated from message multichain.wire.agent.v1.ThreadTranscript
 */
export type ThreadTranscript = Message<"multichain.wire.agent.v1.ThreadTranscript"> & {
  /**
   * @generated from field: multichain.wire.agent.v1.ThreadSummary thread = 1;
   */
  thread?: ThreadSummary | undefined;

  /**
   * @generated from field: repeated multichain.wire.agent.v1.TranscriptTurn turns = 2;
   */
  turns: TranscriptTurn[];
};

/**
 * Describes the message multichain.wire.agent.v1.ThreadTranscript.
 * Use `create(ThreadTranscriptSchema)` to create a new message.
 */
export const ThreadTranscriptSchema: GenMessage<ThreadTranscript> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_history, 3);

