// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file multichain/wire/agent/v1/llm.proto (package multichain.wire.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/agent/v1/llm.proto.
 */
export const file_multichain_wire_agent_v1_llm: GenFile = /*@__PURE__*/
  fileDesc("CiJtdWx0aWNoYWluL3dpcmUvYWdlbnQvdjEvbGxtLnByb3RvEhhtdWx0aWNoYWluLndpcmUuYWdlbnQudjEitQEKC0xsbU92ZXJyaWRlEjcKB3ByaW1hcnkYASABKAsyJi5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuUm9sZU92ZXJyaWRlEjYKBnBvbGljeRgCIAEoCzImLm11bHRpY2hhaW4ud2lyZS5hZ2VudC52MS5Sb2xlT3ZlcnJpZGUSNQoFanVkZ2UYAyABKAsyJi5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuUm9sZU92ZXJyaWRlIjIKDFJvbGVPdmVycmlkZRIQCghwcm92aWRlchgBIAEoCRIQCghtb2RlbF9pZBgCIAEoCWIGcHJvdG8z");

/**
 * Per-request LLM provider override. Empty / missing = use the
 * production preset (env-driven OpenRouter for every role); the
 * production frontend never sets this field, so prod traffic is
 * unaffected.
 *
 * The dev builder view in the frontend exposes a Models section that
 * writes per-role choices into Zustand-backed localStorage and stamps
 * them onto every outgoing AgentRequest. The agent-service reads the
 * override in the loop driver and rebuilds the relevant agent for
 * that turn (sub-millisecond, no I/O) so the per-role model swap
 * takes effect immediately without restarting the service.
 *
 * The override travels per-request rather than living in server state
 * for two reasons: the existing `AgentSwitches` pattern is already
 * per-request (wire field, browser-stored), so this matches; and the
 * blast radius of a leaked dev config is bounded to "this browser"
 * instead of "the whole agent-service process."
 *
 * @generated from message multichain.wire.agent.v1.LlmOverride
 */
export type LlmOverride = Message<"multichain.wire.agent.v1.LlmOverride"> & {
  /**
   * @generated from field: multichain.wire.agent.v1.RoleOverride primary = 1;
   */
  primary?: RoleOverride | undefined;

  /**
   * @generated from field: multichain.wire.agent.v1.RoleOverride policy = 2;
   */
  policy?: RoleOverride | undefined;

  /**
   * @generated from field: multichain.wire.agent.v1.RoleOverride judge = 3;
   */
  judge?: RoleOverride | undefined;
};

/**
 * Describes the message multichain.wire.agent.v1.LlmOverride.
 * Use `create(LlmOverrideSchema)` to create a new message.
 */
export const LlmOverrideSchema: GenMessage<LlmOverride> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_llm, 0);

/**
 * One role's pinned provider + model id. Empty `provider` means
 * "fall through to default" (env-driven OpenRouter for that role).
 * `model_id` is meaningful only when `provider == "local"`; for
 * "openrouter" the env-default model id wins (the dev pain we are
 * solving is OpenRouter latency, not OpenRouter model selection).
 *
 * @generated from message multichain.wire.agent.v1.RoleOverride
 */
export type RoleOverride = Message<"multichain.wire.agent.v1.RoleOverride"> & {
  /**
   * "" | "openrouter" | "local". Unrecognized values are treated as
   * "" by the backend (fall through to env-driven OpenRouter); the
   * wire is permissive on purpose so a future provider can be added
   * without a proto bump on the frontend side.
   *
   * @generated from field: string provider = 1;
   */
  provider: string;

  /**
   * For provider="local": the model id loaded in LM Studio (e.g.
   * "qwen2.5-7b-instruct"). The frontend populates this from the
   * agent-service's GET /agent/local/models proxy. Empty when
   * provider is "" or "openrouter".
   *
   * @generated from field: string model_id = 2;
   */
  modelId: string;
};

/**
 * Describes the message multichain.wire.agent.v1.RoleOverride.
 * Use `create(RoleOverrideSchema)` to create a new message.
 */
export const RoleOverrideSchema: GenMessage<RoleOverride> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_llm, 1);

