// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file multichain/wire/agent/v1/llm.proto (package multichain.wire.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/agent/v1/llm.proto.
 */
export const file_multichain_wire_agent_v1_llm: GenFile = /*@__PURE__*/
  fileDesc("CiJtdWx0aWNoYWluL3dpcmUvYWdlbnQvdjEvbGxtLnByb3RvEhhtdWx0aWNoYWluLndpcmUuYWdlbnQudjEitQEKC0xsbU92ZXJyaWRlEjcKB3ByaW1hcnkYASABKAsyJi5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuUm9sZU92ZXJyaWRlEjYKBnBvbGljeRgCIAEoCzImLm11bHRpY2hhaW4ud2lyZS5hZ2VudC52MS5Sb2xlT3ZlcnJpZGUSNQoFanVkZ2UYAyABKAsyJi5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuUm9sZU92ZXJyaWRlIjIKDFJvbGVPdmVycmlkZRIQCghwcm92aWRlchgBIAEoCRIQCghtb2RlbF9pZBgCIAEoCSI7Cg1Db2RleE92ZXJyaWRlEhAKCG1vZGVsX2lkGAEgASgJEhgKEHJlYXNvbmluZ19lZmZvcnQYAiABKAliBnByb3RvMw");

/**
 * Per-request LLM provider override. Empty / missing = use the
 * production preset (env-driven OpenRouter for every role); the
 * production frontend never sets this field, so prod traffic is
 * unaffected.
 *
 * The dev builder view in the frontend exposes a Models section that
 * writes per-role choices into Zustand-backed localStorage and stamps
 * them onto every outgoing AgentRequest. The agent-service reads the
 * override in the loop driver and rebuilds the relevant agent for
 * that turn (sub-millisecond, no I/O) so the per-role model swap
 * takes effect immediately without restarting the service.
 *
 * The override travels per-request rather than living in server state
 * for two reasons: the existing `AgentSwitches` pattern is already
 * per-request (wire field, browser-stored), so this matches; and the
 * blast radius of a leaked dev config is bounded to "this browser"
 * instead of "the whole agent-service process."
 *
 * @generated from message multichain.wire.agent.v1.LlmOverride
 */
export type LlmOverride = Message<"multichain.wire.agent.v1.LlmOverride"> & {
  /**
   * @generated from field: multichain.wire.agent.v1.RoleOverride primary = 1;
   */
  primary?: RoleOverride | undefined;

  /**
   * @generated from field: multichain.wire.agent.v1.RoleOverride policy = 2;
   */
  policy?: RoleOverride | undefined;

  /**
   * @generated from field: multichain.wire.agent.v1.RoleOverride judge = 3;
   */
  judge?: RoleOverride | undefined;
};

/**
 * Describes the message multichain.wire.agent.v1.LlmOverride.
 * Use `create(LlmOverrideSchema)` to create a new message.
 */
export const LlmOverrideSchema: GenMessage<LlmOverride> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_llm, 0);

/**
 * One role's pinned provider + model id. Empty `provider` means
 * "fall through to default" (env-driven OpenRouter for that role).
 * `model_id` is meaningful only when `provider == "local"`; for
 * "openrouter" the env-default model id wins (the dev pain we are
 * solving is OpenRouter latency, not OpenRouter model selection).
 *
 * @generated from message multichain.wire.agent.v1.RoleOverride
 */
export type RoleOverride = Message<"multichain.wire.agent.v1.RoleOverride"> & {
  /**
   * "" | "openrouter" | "local". Unrecognized values are treated as
   * "" by the backend (fall through to env-driven OpenRouter); the
   * wire is permissive on purpose so a future provider can be added
   * without a proto bump on the frontend side.
   *
   * @generated from field: string provider = 1;
   */
  provider: string;

  /**
   * For provider="local": the model id loaded in LM Studio (e.g.
   * "qwen2.5-7b-instruct"). The frontend populates this from the
   * agent-service's GET /agent/local/models proxy. Empty when
   * provider is "" or "openrouter".
   *
   * @generated from field: string model_id = 2;
   */
  modelId: string;
};

/**
 * Describes the message multichain.wire.agent.v1.RoleOverride.
 * Use `create(RoleOverrideSchema)` to create a new message.
 */
export const RoleOverrideSchema: GenMessage<RoleOverride> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_llm, 1);

/**
 * Per-turn override for the codex runtime's primary model + reasoning
 * effort. Lives separately from `LlmOverride` because codex's tool
 * surface and provider routing are not symmetric with the
 * openrouter/gemini/local triad the pydantic-ai panel exposes; codex
 * always routes through codex-cli, and the only knobs that change
 * turn-to-turn are the model id and the reasoning effort it asks
 * for. Empty fields fall back to `CODEX_PRIMARY_MODEL` /
 * `CODEX_REASONING_EFFORT` env on the agent-service side (which in
 * turn fall back to codex-cli's own defaults when those are unset).
 *
 * The policy + judge roles stay on the `LlmOverride` panel because
 * the constitution agent runs server-side via pydantic-ai regardless
 * of the primary runtime, and the judge is eval-only.
 *
 * @generated from message multichain.wire.agent.v1.CodexOverride
 */
export type CodexOverride = Message<"multichain.wire.agent.v1.CodexOverride"> & {
  /**
   * Codex-CLI model id (e.g. "gpt-5", "gpt-5-mini", "gpt-5-nano",
   * "o3", "o3-mini"). Empty = fall through to env / cli default.
   *
   * @generated from field: string model_id = 1;
   */
  modelId: string;

  /**
   * Codex-CLI reasoning effort: "low" | "medium" | "high". Empty =
   * fall through to env / cli default. Unrecognized values are
   * forwarded as-is (codex-cli rejects them with a clear error;
   * we don't gatekeep here so adding new tiers doesn't need a
   * proto bump).
   *
   * @generated from field: string reasoning_effort = 2;
   */
  reasoningEffort: string;
};

/**
 * Describes the message multichain.wire.agent.v1.CodexOverride.
 * Use `create(CodexOverrideSchema)` to create a new message.
 */
export const CodexOverrideSchema: GenMessage<CodexOverride> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_llm, 2);

