// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file multichain/wire/agent/v1/narrative.proto (package multichain.wire.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProvenanceRef } from "../../shared/v1/provenance_pb";
import { file_multichain_wire_shared_v1_provenance } from "../../shared/v1/provenance_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/agent/v1/narrative.proto.
 */
export const file_multichain_wire_agent_v1_narrative: GenFile = /*@__PURE__*/
  fileDesc("CihtdWx0aWNoYWluL3dpcmUvYWdlbnQvdjEvbmFycmF0aXZlLnByb3RvEhhtdWx0aWNoYWluLndpcmUuYWdlbnQudjEiXwoRTmFycmF0aXZlV2l0aFJlZnMSDAoEdGV4dBgBIAEoCRI8Cgpwcm92ZW5hbmNlGAIgAygLMigubXVsdGljaGFpbi53aXJlLnNoYXJlZC52MS5Qcm92ZW5hbmNlUmVmIl4KEk5hcnJhdGl2ZVJldHJhY3RlZBIMCgR0ZXh0GAEgASgJEg4KBnJlYXNvbhgCIAEoCRIZCgxkZWJ1Z19yZWFzb24YAyABKAlIAIgBAUIPCg1fZGVidWdfcmVhc29uYgZwcm90bzM", [file_multichain_wire_shared_v1_provenance]);

/**
 * Approved free-form prose. May contain inline ${ref:N} tokens the
 * renderer resolves against `provenance` (assembled by the loop
 * from this turn's emitted Claims, concatenated provenance arrays
 * in emission order).
 *
 * @generated from message multichain.wire.agent.v1.NarrativeWithRefs
 */
export type NarrativeWithRefs = Message<"multichain.wire.agent.v1.NarrativeWithRefs"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  /**
   * @generated from field: repeated multichain.wire.shared.v1.ProvenanceRef provenance = 2;
   */
  provenance: ProvenanceRef[];
};

/**
 * Describes the message multichain.wire.agent.v1.NarrativeWithRefs.
 * Use `create(NarrativeWithRefsSchema)` to create a new message.
 */
export const NarrativeWithRefsSchema: GenMessage<NarrativeWithRefs> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_narrative, 0);

/**
 * Narrative the constitution gate retracted. Carries the original
 * text alongside a friendly user-facing reason. `debug_reason` only
 * populated when AGENT_DEBUG_PUBLIC=1 (dev-mode); absent in prod so
 * the wire stays sterile.
 *
 * @generated from message multichain.wire.agent.v1.NarrativeRetracted
 */
export type NarrativeRetracted = Message<"multichain.wire.agent.v1.NarrativeRetracted"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;

  /**
   * @generated from field: optional string debug_reason = 3;
   */
  debugReason?: string | undefined;
};

/**
 * Describes the message multichain.wire.agent.v1.NarrativeRetracted.
 * Use `create(NarrativeRetractedSchema)` to create a new message.
 */
export const NarrativeRetractedSchema: GenMessage<NarrativeRetracted> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_narrative, 1);

