// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file multichain/wire/agent/v1/policy.proto (package multichain.wire.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/agent/v1/policy.proto.
 */
export const file_multichain_wire_agent_v1_policy: GenFile = /*@__PURE__*/
  fileDesc("CiVtdWx0aWNoYWluL3dpcmUvYWdlbnQvdjEvcG9saWN5LnByb3RvEhhtdWx0aWNoYWluLndpcmUuYWdlbnQudjEipgEKDVBvbGljeVZlcmRpY3QSQwoIYXBwcm92ZWQYASABKAsyLy5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuUG9saWN5VmVyZGljdEFwcHJvdmVkSAASRQoJcmV0cmFjdGVkGAIgASgLMjAubXVsdGljaGFpbi53aXJlLmFnZW50LnYxLlBvbGljeVZlcmRpY3RSZXRyYWN0ZWRIAEIJCgd2ZXJkaWN0IhcKFVBvbGljeVZlcmRpY3RBcHByb3ZlZCIoChZQb2xpY3lWZXJkaWN0UmV0cmFjdGVkEg4KBnJlYXNvbhgBIAEoCSJvCghQYXRoU3RlcBINCgVzdGFnZRgBIAEoCRIyCgVzdGF0ZRgCIAEoCzIjLm11bHRpY2hhaW4ud2lyZS5hZ2VudC52MS5QYXRoU3RhdGUSEgoKZWxhcHNlZF91cxgDIAEoDRIMCgRub3RlGAQgASgJIuQBCglQYXRoU3RhdGUSPwoIYXBwcm92ZWQYASABKAsyKy5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuUGF0aFN0YXRlQXBwcm92ZWRIABJBCglyZXRyYWN0ZWQYAiABKAsyLC5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuUGF0aFN0YXRlUmV0cmFjdGVkSAASSgoObm90X2FwcGxpY2FibGUYAyABKAsyMC5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuUGF0aFN0YXRlTm90QXBwbGljYWJsZUgAQgcKBXN0YXRlIhMKEVBhdGhTdGF0ZUFwcHJvdmVkIiQKElBhdGhTdGF0ZVJldHJhY3RlZBIOCgZyZWFzb24YASABKAkiKAoWUGF0aFN0YXRlTm90QXBwbGljYWJsZRIOCgZkZXRhaWwYASABKAliBnByb3RvMw");

/**
 * Output-policy verdict (phase 03 layer 3). v0 stubs to Approved;
 * ship 2 starts producing Retracted on real gate failures.
 *
 * Wire format:
 *   approved  -> {"approved":  {}}
 *   retracted -> {"retracted": {"reason": "..."}}
 *
 * @generated from message multichain.wire.agent.v1.PolicyVerdict
 */
export type PolicyVerdict = Message<"multichain.wire.agent.v1.PolicyVerdict"> & {
  /**
   * @generated from oneof multichain.wire.agent.v1.PolicyVerdict.verdict
   */
  verdict: {
    /**
     * @generated from field: multichain.wire.agent.v1.PolicyVerdictApproved approved = 1;
     */
    value: PolicyVerdictApproved;
    case: "approved";
  } | {
    /**
     * @generated from field: multichain.wire.agent.v1.PolicyVerdictRetracted retracted = 2;
     */
    value: PolicyVerdictRetracted;
    case: "retracted";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message multichain.wire.agent.v1.PolicyVerdict.
 * Use `create(PolicyVerdictSchema)` to create a new message.
 */
export const PolicyVerdictSchema: GenMessage<PolicyVerdict> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_policy, 0);

/**
 * @generated from message multichain.wire.agent.v1.PolicyVerdictApproved
 */
export type PolicyVerdictApproved = Message<"multichain.wire.agent.v1.PolicyVerdictApproved"> & {
};

/**
 * Describes the message multichain.wire.agent.v1.PolicyVerdictApproved.
 * Use `create(PolicyVerdictApprovedSchema)` to create a new message.
 */
export const PolicyVerdictApprovedSchema: GenMessage<PolicyVerdictApproved> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_policy, 1);

/**
 * @generated from message multichain.wire.agent.v1.PolicyVerdictRetracted
 */
export type PolicyVerdictRetracted = Message<"multichain.wire.agent.v1.PolicyVerdictRetracted"> & {
  /**
   * @generated from field: string reason = 1;
   */
  reason: string;
};

/**
 * Describes the message multichain.wire.agent.v1.PolicyVerdictRetracted.
 * Use `create(PolicyVerdictRetractedSchema)` to create a new message.
 */
export const PolicyVerdictRetractedSchema: GenMessage<PolicyVerdictRetracted> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_policy, 2);

/**
 * One step in the gate's execution path. Built by `PathBuilder`
 * in `policy.rs` as each switch's leg runs (or skips). The
 * frontend's builder view renders these as a vertical timeline
 * inside `GatePathTimeline.tsx`.
 *
 * @generated from message multichain.wire.agent.v1.PathStep
 */
export type PathStep = Message<"multichain.wire.agent.v1.PathStep"> & {
  /**
   * Dotted stage id (e.g. "claim.stay_in_role",
   * "narrative.cross_check.paraphrase_aware_match").
   *
   * @generated from field: string stage = 1;
   */
  stage: string;

  /**
   * @generated from field: multichain.wire.agent.v1.PathState state = 2;
   */
  state?: PathState | undefined;

  /**
   * Wallclock microseconds the step took. For visual ordering
   * only; determinism not promised across runs.
   *
   * @generated from field: uint32 elapsed_us = 3;
   */
  elapsedUs: number;

  /**
   * Single-line note: what was checked, what verdict.
   *
   * @generated from field: string note = 4;
   */
  note: string;
};

/**
 * Describes the message multichain.wire.agent.v1.PathStep.
 * Use `create(PathStepSchema)` to create a new message.
 */
export const PathStepSchema: GenMessage<PathStep> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_policy, 3);

/**
 * One leg's verdict. NotApplicable covers both "switch off" and
 * "couldn't run" (malformed extraction, parse failure).
 *
 * Wire format:
 *   approved      -> {"approved":      {}}
 *   retracted     -> {"retracted":     {"reason": "..."}}
 *   notApplicable -> {"notApplicable": {"detail": "..."}}
 *
 * @generated from message multichain.wire.agent.v1.PathState
 */
export type PathState = Message<"multichain.wire.agent.v1.PathState"> & {
  /**
   * @generated from oneof multichain.wire.agent.v1.PathState.state
   */
  state: {
    /**
     * @generated from field: multichain.wire.agent.v1.PathStateApproved approved = 1;
     */
    value: PathStateApproved;
    case: "approved";
  } | {
    /**
     * @generated from field: multichain.wire.agent.v1.PathStateRetracted retracted = 2;
     */
    value: PathStateRetracted;
    case: "retracted";
  } | {
    /**
     * @generated from field: multichain.wire.agent.v1.PathStateNotApplicable not_applicable = 3;
     */
    value: PathStateNotApplicable;
    case: "notApplicable";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message multichain.wire.agent.v1.PathState.
 * Use `create(PathStateSchema)` to create a new message.
 */
export const PathStateSchema: GenMessage<PathState> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_policy, 4);

/**
 * @generated from message multichain.wire.agent.v1.PathStateApproved
 */
export type PathStateApproved = Message<"multichain.wire.agent.v1.PathStateApproved"> & {
};

/**
 * Describes the message multichain.wire.agent.v1.PathStateApproved.
 * Use `create(PathStateApprovedSchema)` to create a new message.
 */
export const PathStateApprovedSchema: GenMessage<PathStateApproved> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_policy, 5);

/**
 * @generated from message multichain.wire.agent.v1.PathStateRetracted
 */
export type PathStateRetracted = Message<"multichain.wire.agent.v1.PathStateRetracted"> & {
  /**
   * @generated from field: string reason = 1;
   */
  reason: string;
};

/**
 * Describes the message multichain.wire.agent.v1.PathStateRetracted.
 * Use `create(PathStateRetractedSchema)` to create a new message.
 */
export const PathStateRetractedSchema: GenMessage<PathStateRetracted> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_policy, 6);

/**
 * @generated from message multichain.wire.agent.v1.PathStateNotApplicable
 */
export type PathStateNotApplicable = Message<"multichain.wire.agent.v1.PathStateNotApplicable"> & {
  /**
   * @generated from field: string detail = 1;
   */
  detail: string;
};

/**
 * Describes the message multichain.wire.agent.v1.PathStateNotApplicable.
 * Use `create(PathStateNotApplicableSchema)` to create a new message.
 */
export const PathStateNotApplicableSchema: GenMessage<PathStateNotApplicable> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_policy, 7);

