// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file multichain/wire/agent/v1/session.proto (package multichain.wire.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ViewContext } from "./entity_pb";
import { file_multichain_wire_agent_v1_entity } from "./entity_pb";
import type { LlmOverride } from "./llm_pb";
import { file_multichain_wire_agent_v1_llm } from "./llm_pb";
import type { AgentSwitches } from "./switches_pb";
import { file_multichain_wire_agent_v1_switches } from "./switches_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/agent/v1/session.proto.
 */
export const file_multichain_wire_agent_v1_session: GenFile = /*@__PURE__*/
  fileDesc("CiZtdWx0aWNoYWluL3dpcmUvYWdlbnQvdjEvc2Vzc2lvbi5wcm90bxIYbXVsdGljaGFpbi53aXJlLmFnZW50LnYxIqECCgxBZ2VudFJlcXVlc3QSFQoNdXNlcl9xdWVzdGlvbhgBIAEoCRI2Cgdjb250ZXh0GAIgASgLMiUubXVsdGljaGFpbi53aXJlLmFnZW50LnYxLlZpZXdDb250ZXh0EhYKCXRocmVhZF9pZBgDIAEoCUgAiAEBEjkKCHN3aXRjaGVzGAQgASgLMicubXVsdGljaGFpbi53aXJlLmFnZW50LnYxLkFnZW50U3dpdGNoZXMSEgoKc2hvd190cmFjZRgFIAEoCBIQCghydW5fdHlwZRgGIAEoCRI7CgxsbG1fb3ZlcnJpZGUYByABKAsyJS5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuTGxtT3ZlcnJpZGVCDAoKX3RocmVhZF9pZCJuCglBZ2VudERvbmUSEgoKZWxhcHNlZF9tcxgBIAEoDRIQCgh0cmFjZV9pZBgCIAEoCRI7Cgxyb2xlX3RpbWluZ3MYAyABKAsyJS5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuUm9sZVRpbWluZ3MiRgoLUm9sZVRpbWluZ3MSEgoKcHJpbWFyeV9tcxgBIAEoDRIRCglwb2xpY3lfbXMYAiABKA0SEAoIanVkZ2VfbXMYAyABKA1iBnByb3RvMw", [file_multichain_wire_agent_v1_entity, file_multichain_wire_agent_v1_llm, file_multichain_wire_agent_v1_switches]);

/**
 * User question + ViewContext. `thread_id` is None on the first
 * send of a fresh conversation; the backend mints one and returns
 * it. Subsequent follow-ups echo the prior thread_id.
 *
 * `switches` defaults to the production preset (everything except
 * ground_truth_match). `show_trace` controls whether GatePath
 * frames are emitted; trace is always built and ledgered regardless.
 *
 * `run_type` discriminates production traffic from eval-driven
 * traffic in the OTel/Langfuse/ClickHouse trace store. Empty
 * string maps to "production" on the agent side. The eval CLI
 * sets "eval" so analytics filters can exclude eval volume from
 * production aggregates without running a separate agent process.
 * Conventional values: "" | "production" | "eval" | "dev". Other
 * values pass through unchanged so callers can extend without a
 * proto bump.
 *
 * @generated from message multichain.wire.agent.v1.AgentRequest
 */
export type AgentRequest = Message<"multichain.wire.agent.v1.AgentRequest"> & {
  /**
   * @generated from field: string user_question = 1;
   */
  userQuestion: string;

  /**
   * @generated from field: multichain.wire.agent.v1.ViewContext context = 2;
   */
  context?: ViewContext | undefined;

  /**
   * @generated from field: optional string thread_id = 3;
   */
  threadId?: string | undefined;

  /**
   * @generated from field: multichain.wire.agent.v1.AgentSwitches switches = 4;
   */
  switches?: AgentSwitches | undefined;

  /**
   * @generated from field: bool show_trace = 5;
   */
  showTrace: boolean;

  /**
   * @generated from field: string run_type = 6;
   */
  runType: string;

  /**
   * Dev-only per-role LLM provider override. Empty / missing = use
   * the production preset (env-driven OpenRouter). Set by the
   * frontend builder view's Models section; production frontend
   * never populates this field. See llm.proto for shape.
   *
   * @generated from field: multichain.wire.agent.v1.LlmOverride llm_override = 7;
   */
  llmOverride?: LlmOverride | undefined;
};

/**
 * Describes the message multichain.wire.agent.v1.AgentRequest.
 * Use `create(AgentRequestSchema)` to create a new message.
 */
export const AgentRequestSchema: GenMessage<AgentRequest> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_session, 0);

/**
 * Final SSE event payload. Emitted as the `done` event by the SSE
 * handler. `elapsed_ms` is u32 (caps at ~50 days). `trace_id` is the
 * 32-hex-char OTel trace id for this turn (Ship 1 of agent-
 * observability, ADR 13); the frontend uses it to deep-link into
 * Langfuse for the visual flame graph. Empty string means trace
 * emission was disabled (OTEL_SDK_DISABLED) or otherwise unavailable.
 *
 * `role_timings` carries the wall-time spent in each LLM role for
 * this turn (sum across multiple calls within the same role on the
 * same turn; the policy bucket fires multiple times per turn for
 * constitution gates + repeat detection, so the sum is the useful
 * "how much wall time did this role consume" view). Builder view's
 * Models panel reads it back to surface "last call elapsed" under
 * each role row, so a dev sees which role is dragging a turn
 * without trawling docker logs.
 *
 * @generated from message multichain.wire.agent.v1.AgentDone
 */
export type AgentDone = Message<"multichain.wire.agent.v1.AgentDone"> & {
  /**
   * @generated from field: uint32 elapsed_ms = 1;
   */
  elapsedMs: number;

  /**
   * @generated from field: string trace_id = 2;
   */
  traceId: string;

  /**
   * @generated from field: multichain.wire.agent.v1.RoleTimings role_timings = 3;
   */
  roleTimings?: RoleTimings | undefined;
};

/**
 * Describes the message multichain.wire.agent.v1.AgentDone.
 * Use `create(AgentDoneSchema)` to create a new message.
 */
export const AgentDoneSchema: GenMessage<AgentDone> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_session, 1);

/**
 * Per-role wall-time tally for one turn. Values are integer
 * milliseconds; zero means "no calls fired in that role this turn"
 * (e.g. judge role isn't on the chat path today, so it stays 0).
 *
 * @generated from message multichain.wire.agent.v1.RoleTimings
 */
export type RoleTimings = Message<"multichain.wire.agent.v1.RoleTimings"> & {
  /**
   * @generated from field: uint32 primary_ms = 1;
   */
  primaryMs: number;

  /**
   * @generated from field: uint32 policy_ms = 2;
   */
  policyMs: number;

  /**
   * @generated from field: uint32 judge_ms = 3;
   */
  judgeMs: number;
};

/**
 * Describes the message multichain.wire.agent.v1.RoleTimings.
 * Use `create(RoleTimingsSchema)` to create a new message.
 */
export const RoleTimingsSchema: GenMessage<RoleTimings> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_session, 2);

