// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file multichain/wire/agent/v1/session.proto (package multichain.wire.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ViewContext } from "./entity_pb";
import { file_multichain_wire_agent_v1_entity } from "./entity_pb";
import type { LlmOverride } from "./llm_pb";
import { file_multichain_wire_agent_v1_llm } from "./llm_pb";
import type { AgentSwitches } from "./switches_pb";
import { file_multichain_wire_agent_v1_switches } from "./switches_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/agent/v1/session.proto.
 */
export const file_multichain_wire_agent_v1_session: GenFile = /*@__PURE__*/
  fileDesc("CiZtdWx0aWNoYWluL3dpcmUvYWdlbnQvdjEvc2Vzc2lvbi5wcm90bxIYbXVsdGljaGFpbi53aXJlLmFnZW50LnYxIqECCgxBZ2VudFJlcXVlc3QSFQoNdXNlcl9xdWVzdGlvbhgBIAEoCRI2Cgdjb250ZXh0GAIgASgLMiUubXVsdGljaGFpbi53aXJlLmFnZW50LnYxLlZpZXdDb250ZXh0EhYKCXRocmVhZF9pZBgDIAEoCUgAiAEBEjkKCHN3aXRjaGVzGAQgASgLMicubXVsdGljaGFpbi53aXJlLmFnZW50LnYxLkFnZW50U3dpdGNoZXMSEgoKc2hvd190cmFjZRgFIAEoCBIQCghydW5fdHlwZRgGIAEoCRI7CgxsbG1fb3ZlcnJpZGUYByABKAsyJS5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuTGxtT3ZlcnJpZGVCDAoKX3RocmVhZF9pZCJKChNBZ2VudFNlc3Npb25TdGFydGVkEhIKCnNlc3Npb25faWQYASABKAkSEQoJdGhyZWFkX2lkGAIgASgJEgwKBHR1cm4YAyABKA0iRQoJQWdlbnREb25lEhIKCnNlc3Npb25faWQYASABKAkSEgoKZWxhcHNlZF9tcxgCIAEoDRIQCgh0cmFjZV9pZBgDIAEoCWIGcHJvdG8z", [file_multichain_wire_agent_v1_entity, file_multichain_wire_agent_v1_llm, file_multichain_wire_agent_v1_switches]);

/**
 * User question + ViewContext. `thread_id` is None on the first
 * send of a fresh conversation; the backend mints one and returns
 * it. Subsequent follow-ups echo the prior thread_id.
 *
 * `switches` defaults to the production preset (everything except
 * ground_truth_match). `show_trace` controls whether GatePath
 * frames are emitted; trace is always built and ledgered regardless.
 *
 * `run_type` discriminates production traffic from eval-driven
 * traffic in the OTel/Langfuse/ClickHouse trace store. Empty
 * string maps to "production" on the agent side. The eval CLI
 * sets "eval" so analytics filters can exclude eval volume from
 * production aggregates without running a separate agent process.
 * Conventional values: "" | "production" | "eval" | "dev". Other
 * values pass through unchanged so callers can extend without a
 * proto bump.
 *
 * @generated from message multichain.wire.agent.v1.AgentRequest
 */
export type AgentRequest = Message<"multichain.wire.agent.v1.AgentRequest"> & {
  /**
   * @generated from field: string user_question = 1;
   */
  userQuestion: string;

  /**
   * @generated from field: multichain.wire.agent.v1.ViewContext context = 2;
   */
  context?: ViewContext | undefined;

  /**
   * @generated from field: optional string thread_id = 3;
   */
  threadId?: string | undefined;

  /**
   * @generated from field: multichain.wire.agent.v1.AgentSwitches switches = 4;
   */
  switches?: AgentSwitches | undefined;

  /**
   * @generated from field: bool show_trace = 5;
   */
  showTrace: boolean;

  /**
   * @generated from field: string run_type = 6;
   */
  runType: string;

  /**
   * Dev-only per-role LLM provider override. Empty / missing = use
   * the production preset (env-driven OpenRouter). Set by the
   * frontend builder view's Models section; production frontend
   * never populates this field. See llm.proto for shape.
   *
   * @generated from field: multichain.wire.agent.v1.LlmOverride llm_override = 7;
   */
  llmOverride?: LlmOverride | undefined;
};

/**
 * Describes the message multichain.wire.agent.v1.AgentRequest.
 * Use `create(AgentRequestSchema)` to create a new message.
 */
export const AgentRequestSchema: GenMessage<AgentRequest> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_session, 0);

/**
 * Returned synchronously from POST /agent/ask. `session_id` is
 * per-turn (drives the SSE GET, ledger row group). `thread_id`
 * is the persistent conversation handle. `turn` is 0 on the first
 * turn, increments on follow-ups.
 *
 * @generated from message multichain.wire.agent.v1.AgentSessionStarted
 */
export type AgentSessionStarted = Message<"multichain.wire.agent.v1.AgentSessionStarted"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string thread_id = 2;
   */
  threadId: string;

  /**
   * @generated from field: uint32 turn = 3;
   */
  turn: number;
};

/**
 * Describes the message multichain.wire.agent.v1.AgentSessionStarted.
 * Use `create(AgentSessionStartedSchema)` to create a new message.
 */
export const AgentSessionStartedSchema: GenMessage<AgentSessionStarted> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_session, 1);

/**
 * Final SSE event payload. Emitted as the `done` event by the SSE
 * handler. `elapsed_ms` is u32 (caps at ~50 days). `trace_id` is the
 * 32-hex-char OTel trace id for this turn (Ship 1 of agent-
 * observability, ADR 13); the frontend uses it to deep-link into
 * Langfuse for the visual flame graph. Empty string means trace
 * emission was disabled (OTEL_SDK_DISABLED) or otherwise unavailable.
 *
 * @generated from message multichain.wire.agent.v1.AgentDone
 */
export type AgentDone = Message<"multichain.wire.agent.v1.AgentDone"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: uint32 elapsed_ms = 2;
   */
  elapsedMs: number;

  /**
   * @generated from field: string trace_id = 3;
   */
  traceId: string;
};

/**
 * Describes the message multichain.wire.agent.v1.AgentDone.
 * Use `create(AgentDoneSchema)` to create a new message.
 */
export const AgentDoneSchema: GenMessage<AgentDone> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_session, 2);

