// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file multichain/wire/agent/v1/sse.proto (package multichain.wire.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { PathStep, PolicyVerdict } from "./policy_pb";
import { file_multichain_wire_agent_v1_policy } from "./policy_pb";
import type { AgentSwitches } from "./switches_pb";
import { file_multichain_wire_agent_v1_switches } from "./switches_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/agent/v1/sse.proto.
 */
export const file_multichain_wire_agent_v1_sse: GenFile = /*@__PURE__*/
  fileDesc("CiJtdWx0aWNoYWluL3dpcmUvYWdlbnQvdjEvc3NlLnByb3RvEhhtdWx0aWNoYWluLndpcmUuYWdlbnQudjEiKQoIUHJvZ3Jlc3MSDQoFcGhhc2UYASABKAkSDgoGZGV0YWlsGAIgASgJIkYKBUVycm9yEg8KB21lc3NhZ2UYASABKAkSGgoNZGVidWdfbWVzc2FnZRgCIAEoCUgAiAEBQhAKDl9kZWJ1Z19tZXNzYWdlIskBCghHYXRlUGF0aBIPCgdjaGFubmVsGAEgASgJEjkKCHN3aXRjaGVzGAIgASgLMicubXVsdGljaGFpbi53aXJlLmFnZW50LnYxLkFnZW50U3dpdGNoZXMSMQoFc3RlcHMYAyADKAsyIi5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuUGF0aFN0ZXASPgoNZmluYWxfdmVyZGljdBgEIAEoCzInLm11bHRpY2hhaW4ud2lyZS5hZ2VudC52MS5Qb2xpY3lWZXJkaWN0YgZwcm90bzM", [file_multichain_wire_agent_v1_policy, file_multichain_wire_agent_v1_switches]);

/**
 * Lightweight progress ping. `phase` + `detail` are free-form strings
 * the frontend can render as a status line.
 *
 * @generated from message multichain.wire.agent.v1.Progress
 */
export type Progress = Message<"multichain.wire.agent.v1.Progress"> & {
  /**
   * @generated from field: string phase = 1;
   */
  phase: string;

  /**
   * @generated from field: string detail = 2;
   */
  detail: string;
};

/**
 * Describes the message multichain.wire.agent.v1.Progress.
 * Use `create(ProgressSchema)` to create a new message.
 */
export const ProgressSchema: GenMessage<Progress> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_sse, 0);

/**
 * Terminal turn-level error. The SSE handler renders this as an
 * `error` event before the closing `done`. `debug_message` only
 * populated when AGENT_DEBUG_PUBLIC=1.
 *
 * @generated from message multichain.wire.agent.v1.Error
 */
export type Error = Message<"multichain.wire.agent.v1.Error"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: optional string debug_message = 2;
   */
  debugMessage?: string | undefined;
};

/**
 * Describes the message multichain.wire.agent.v1.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_sse, 1);

/**
 * Full path of one channel's gate run. Emitted as `gatePath` SSE
 * frame when AgentRequest.show_trace=true. Trace is always built
 * and ledgered; the frame is wire-only.
 *
 * @generated from message multichain.wire.agent.v1.GatePath
 */
export type GatePath = Message<"multichain.wire.agent.v1.GatePath"> & {
  /**
   * @generated from field: string channel = 1;
   */
  channel: string;

  /**
   * @generated from field: multichain.wire.agent.v1.AgentSwitches switches = 2;
   */
  switches?: AgentSwitches | undefined;

  /**
   * @generated from field: repeated multichain.wire.agent.v1.PathStep steps = 3;
   */
  steps: PathStep[];

  /**
   * @generated from field: multichain.wire.agent.v1.PolicyVerdict final_verdict = 4;
   */
  finalVerdict?: PolicyVerdict | undefined;
};

/**
 * Describes the message multichain.wire.agent.v1.GatePath.
 * Use `create(GatePathSchema)` to create a new message.
 */
export const GatePathSchema: GenMessage<GatePath> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_sse, 2);

