// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file multichain/wire/agent/v1/switches.proto (package multichain.wire.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/agent/v1/switches.proto.
 */
export const file_multichain_wire_agent_v1_switches: GenFile = /*@__PURE__*/
  fileDesc("CidtdWx0aWNoYWluL3dpcmUvYWdlbnQvdjEvc3dpdGNoZXMucHJvdG8SGG11bHRpY2hhaW4ud2lyZS5hZ2VudC52MSKJAgoNQWdlbnRTd2l0Y2hlcxJCCgxzdGF5X2luX3JvbGUYASABKAsyLC5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuU3RheUluUm9sZVN3aXRjaGVzEhYKDmRvbnRfZmFicmljYXRlGAIgASgIEkEKC2Nyb3NzX2NoZWNrGAMgASgLMiwubXVsdGljaGFpbi53aXJlLmFnZW50LnYxLkNyb3NzQ2hlY2tTd2l0Y2hlcxIcChRkb250X3JlcGVhdF95b3Vyc2VsZhgEIAEoCBI7CghjaGFubmVscxgFIAEoCzIpLm11bHRpY2hhaW4ud2lyZS5hZ2VudC52MS5DaGFubmVsU3dpdGNoZXMiWAoPQ2hhbm5lbFN3aXRjaGVzEiAKGG5hcnJhdGl2ZV9vdXRwdXRfZW5hYmxlZBgBIAEoCBIjChtleHRlcm5hbF90ZXh0X2lucHV0X2VuYWJsZWQYAiABKAgi+AEKElN0YXlJblJvbGVTd2l0Y2hlcxIlCh1kZWZlbmRfY2hhdF90ZW1wbGF0ZV9zcG9vZmluZxgBIAEoCBIhChlkZWZlbmRfY29uc3RpdHV0aW9uX2p1ZGdlGAIgASgIEhsKE2RlZmVuZF9wZXJzb25hX3N3YXAYAyABKAgSIQoZZGVmZW5kX2RlY29kZV9hbmRfZXhlY3V0ZRgEIAEoCBIeChZkZWZlbmRfaWRlbnRpdHlfcmV2ZWFsGAUgASgIEhkKEWRlZmVuZF9vZmZfZG9tYWluGAYgASgIEh0KFWRlZmVuZF9tZW1vX2luamVjdGlvbhgHIAEoCCJQChJDcm9zc0NoZWNrU3dpdGNoZXMSHgoWcGFyYXBocmFzZV9hd2FyZV9tYXRjaBgBIAEoCBIaChJncm91bmRfdHJ1dGhfbWF0Y2gYAiABKAhiBnByb3RvMw");

/**
 * Ship 3.5 ablation switches. Each field is a behavior contract;
 * when true, the agent has that behavior. Defaults reproduce the
 * production preset (everything except ground_truth_match).
 *
 * SECURITY: switches are reachable from any client. Project is a
 * builder portfolio, not a product; we explicitly do not hide internals.
 * If this code ever serves real end-user traffic, lock the switch
 * surface server-side.
 *
 * @generated from message multichain.wire.agent.v1.AgentSwitches
 */
export type AgentSwitches = Message<"multichain.wire.agent.v1.AgentSwitches"> & {
  /**
   * Identity, scope, conduct rules. Sub-message so each defense
   * surface can be ablated independently for the article-path
   * comparison work; the legacy single-bool meaning is preserved
   * by `defend_constitution_judge` (the LLM-side gate that the old
   * bool gated). See #35.
   *
   * @generated from field: multichain.wire.agent.v1.StayInRoleSwitches stay_in_role = 1;
   */
  stayInRole?: StayInRoleSwitches | undefined;

  /**
   * Numbers and entities in claims must come from real tool output.
   * With this off, the model can invent values that no tool returned.
   *
   * @generated from field: bool dont_fabricate = 2;
   */
  dontFabricate: boolean;

  /**
   * Three sub-modes of consistency check across the chain.
   *
   * @generated from field: multichain.wire.agent.v1.CrossCheckSwitches cross_check = 3;
   */
  crossCheck?: CrossCheckSwitches | undefined;

  /**
   * Ship 4: agent recognizes repeat questions in the same thread,
   * re-fetches the prior turn's primitives, deterministically diffs
   * against the prior outputs, and surfaces only what changed.
   *
   * @generated from field: bool dont_repeat_yourself = 4;
   */
  dontRepeatYourself: boolean;

  /**
   * Cockpit: per-channel I/O toggles for the agent's communication
   * surface. Each channel pairs a switch with a deterministic
   * observable (an `mcae.turn.channels.*` span attribute) so eval
   * probes can assert the off-state actually held.
   *
   * @generated from field: multichain.wire.agent.v1.ChannelSwitches channels = 5;
   */
  channels?: ChannelSwitches | undefined;
};

/**
 * Describes the message multichain.wire.agent.v1.AgentSwitches.
 * Use `create(AgentSwitchesSchema)` to create a new message.
 */
export const AgentSwitchesSchema: GenMessage<AgentSwitches> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_switches, 0);

/**
 * Cockpit-style I/O channel toggles. Each switch controls one of
 * the agent's input or output text surfaces. Defaults are the
 * production preset (every channel on); proto3 false default
 * deliberately puts the unsafe state behind explicit construction
 * so a caller forgetting a field gets a noticeably restrictive
 * agent rather than a silently-leaky one.
 *
 * @generated from message multichain.wire.agent.v1.ChannelSwitches
 */
export type ChannelSwitches = Message<"multichain.wire.agent.v1.ChannelSwitches"> & {
  /**
   * When false, the agent's free-form Narrative output is replaced
   * with empty text at the loop driver before the SSE Narrative
   * frame is emitted. The model still generates prose; we drop it
   * before any consumer sees it. The `mcae.narrative.emitted` span
   * still fires (with `length_chars=0` and `narrative.suppressed
   * =true`) so probes can assert the off-state held without
   * inspecting frontend state.
   *
   * Use cases: stress-test whether the agent can carry a turn
   * through Claim chips alone; remove Narrative as a potential
   * exfil channel for prompt-injected text; measure how much of
   * a turn's value lives in structured Claims vs interpretive prose.
   *
   * @generated from field: bool narrative_output_enabled = 1;
   */
  narrativeOutputEnabled: boolean;

  /**
   * When false, primitive tool outputs are sanitized before being
   * wrapped in <external_data>: every string field outside the
   * constrained-format allowlist (base58 address, enum role, mint
   * id) is replaced with a placeholder. Today no primitive emits
   * untrusted text so this switch is forward-looking, but it is
   * wired now so future memo or tag primitives slot in without a
   * schema change.
   *
   * @generated from field: bool external_text_input_enabled = 2;
   */
  externalTextInputEnabled: boolean;
};

/**
 * Describes the message multichain.wire.agent.v1.ChannelSwitches.
 * Use `create(ChannelSwitchesSchema)` to create a new message.
 */
export const ChannelSwitchesSchema: GenMessage<ChannelSwitches> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_switches, 1);

/**
 * Per-defense ablation surface for the "stay in role" family.
 * Each field is a defense the article toggles to measure which
 * vectors the underlying model resists without our enforcement.
 *
 * Defaults: caller MUST set every field explicitly (proto3 false
 * default is deliberately the unsafe state so a caller forgetting
 * a field reports raw model behavior, not an accidental "all
 * defenses on by silent default").
 *
 * @generated from message multichain.wire.agent.v1.StayInRoleSwitches
 */
export type StayInRoleSwitches = Message<"multichain.wire.agent.v1.StayInRoleSwitches"> & {
  /**
   * Boundary rejection of chat-template tokens, closing pseudo-tags,
   * HTML script tags. Deterministic input rail; when off, unsafe
   * input flows to agent.run() unchanged. See `boundary.py` and #33.
   *
   * @generated from field: bool defend_chat_template_spoofing = 1;
   */
  defendChatTemplateSpoofing: boolean;

  /**
   * LLM-side constitution gate that judges Claim + Narrative against
   * policy_v4 rules. This preserves the legacy semantic of the
   * bool stay_in_role: when off, the constitution gate spans
   * (mcae.gate.constitution, mcae.gate.narrative_constitution) are
   * not emitted and gate verdicts default to approved.
   *
   * @generated from field: bool defend_constitution_judge = 2;
   */
  defendConstitutionJudge: boolean;

  /**
   * Drops `defense:user_question_untrusted`. The rule covers
   * persona-swap and decode-and-execute together (one tightly
   * worded paragraph), so both `defend_persona_swap` and
   * `defend_decode_and_execute` map to the same drop. Either flag
   * off keeps the rule; both off drops it.
   *
   * @generated from field: bool defend_persona_swap = 3;
   */
  defendPersonaSwap: boolean;

  /**
   * @generated from field: bool defend_decode_and_execute = 4;
   */
  defendDecodeAndExecute: boolean;

  /**
   * Drops `defense:identity`. When off the agent will name the
   * underlying LLM if asked.
   *
   * @generated from field: bool defend_identity_reveal = 5;
   */
  defendIdentityReveal: boolean;

  /**
   * Drops `defense:off_domain`. When off the agent's "decline
   * off-topic" rule disappears.
   *
   * @generated from field: bool defend_off_domain = 6;
   */
  defendOffDomain: boolean;

  /**
   * Drops `defense:memo_injection`. When off the agent loses the
   * explicit rule that <external_data> blocks are data not
   * instructions; `wrap_external_data` still fires but the
   * model-side defense-in-depth is gone.
   *
   * @generated from field: bool defend_memo_injection = 7;
   */
  defendMemoInjection: boolean;
};

/**
 * Describes the message multichain.wire.agent.v1.StayInRoleSwitches.
 * Use `create(StayInRoleSwitchesSchema)` to create a new message.
 */
export const StayInRoleSwitchesSchema: GenMessage<StayInRoleSwitches> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_switches, 2);

/**
 * Sub-modes of cross_check. Two independent toggles after ship 5a
 * retired text_match. Both advisory in the strict merge.
 *
 * @generated from message multichain.wire.agent.v1.CrossCheckSwitches
 */
export type CrossCheckSwitches = Message<"multichain.wire.agent.v1.CrossCheckSwitches"> & {
  /**
   * LLM-driven coherence check: does the model's prose use its
   * cited chip values consistently? Recall-based, paraphrase-robust.
   *
   * @generated from field: bool paraphrase_aware_match = 1;
   */
  paraphraseAwareMatch: boolean;

  /**
   * Re-query the source-of-truth database, verify prose against
   * actual data. NOT recall-based. Stub in ship 3.5; the real
   * implementation lands in ship 5b with warehouse primitives.
   *
   * @generated from field: bool ground_truth_match = 2;
   */
  groundTruthMatch: boolean;
};

/**
 * Describes the message multichain.wire.agent.v1.CrossCheckSwitches.
 * Use `create(CrossCheckSwitchesSchema)` to create a new message.
 */
export const CrossCheckSwitchesSchema: GenMessage<CrossCheckSwitches> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_switches, 3);

