// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file multichain/wire/agent/v1/switches.proto (package multichain.wire.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/agent/v1/switches.proto.
 */
export const file_multichain_wire_agent_v1_switches: GenFile = /*@__PURE__*/
  fileDesc("CidtdWx0aWNoYWluL3dpcmUvYWdlbnQvdjEvc3dpdGNoZXMucHJvdG8SGG11bHRpY2hhaW4ud2lyZS5hZ2VudC52MSKeAQoNQWdlbnRTd2l0Y2hlcxIUCgxzdGF5X2luX3JvbGUYASABKAgSFgoOZG9udF9mYWJyaWNhdGUYAiABKAgSQQoLY3Jvc3NfY2hlY2sYAyABKAsyLC5tdWx0aWNoYWluLndpcmUuYWdlbnQudjEuQ3Jvc3NDaGVja1N3aXRjaGVzEhwKFGRvbnRfcmVwZWF0X3lvdXJzZWxmGAQgASgIIlAKEkNyb3NzQ2hlY2tTd2l0Y2hlcxIeChZwYXJhcGhyYXNlX2F3YXJlX21hdGNoGAEgASgIEhoKEmdyb3VuZF90cnV0aF9tYXRjaBgCIAEoCGIGcHJvdG8z");

/**
 * Ship 3.5 ablation switches. Each field is a behavior contract;
 * when true, the agent has that behavior. Defaults reproduce the
 * production preset (everything except ground_truth_match).
 *
 * SECURITY: switches are reachable from any client. Project is a
 * builder portfolio, not a product; we explicitly do not hide internals.
 * If this code ever serves real end-user traffic, lock the switch
 * surface server-side.
 *
 * @generated from message multichain.wire.agent.v1.AgentSwitches
 */
export type AgentSwitches = Message<"multichain.wire.agent.v1.AgentSwitches"> & {
  /**
   * Identity, scope, conduct rules. With this off, the model is
   * whatever the underlying LLM is.
   *
   * @generated from field: bool stay_in_role = 1;
   */
  stayInRole: boolean;

  /**
   * Numbers and entities in claims must come from real tool output.
   * With this off, the model can invent values that no tool returned.
   *
   * @generated from field: bool dont_fabricate = 2;
   */
  dontFabricate: boolean;

  /**
   * Three sub-modes of consistency check across the chain.
   *
   * @generated from field: multichain.wire.agent.v1.CrossCheckSwitches cross_check = 3;
   */
  crossCheck?: CrossCheckSwitches | undefined;

  /**
   * Ship 4: agent recognizes repeat questions in the same thread,
   * re-fetches the prior turn's primitives, deterministically diffs
   * against the prior outputs, and surfaces only what changed.
   *
   * @generated from field: bool dont_repeat_yourself = 4;
   */
  dontRepeatYourself: boolean;
};

/**
 * Describes the message multichain.wire.agent.v1.AgentSwitches.
 * Use `create(AgentSwitchesSchema)` to create a new message.
 */
export const AgentSwitchesSchema: GenMessage<AgentSwitches> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_switches, 0);

/**
 * Sub-modes of cross_check. Two independent toggles after ship 5a
 * retired text_match. Both advisory in the strict merge.
 *
 * @generated from message multichain.wire.agent.v1.CrossCheckSwitches
 */
export type CrossCheckSwitches = Message<"multichain.wire.agent.v1.CrossCheckSwitches"> & {
  /**
   * LLM-driven coherence check: does the model's prose use its
   * cited chip values consistently? Recall-based, paraphrase-robust.
   *
   * @generated from field: bool paraphrase_aware_match = 1;
   */
  paraphraseAwareMatch: boolean;

  /**
   * Re-query the source-of-truth database, verify prose against
   * actual data. NOT recall-based. Stub in ship 3.5; the real
   * implementation lands in ship 5b with warehouse primitives.
   *
   * @generated from field: bool ground_truth_match = 2;
   */
  groundTruthMatch: boolean;
};

/**
 * Describes the message multichain.wire.agent.v1.CrossCheckSwitches.
 * Use `create(CrossCheckSwitchesSchema)` to create a new message.
 */
export const CrossCheckSwitchesSchema: GenMessage<CrossCheckSwitches> = /*@__PURE__*/
  messageDesc(file_multichain_wire_agent_v1_switches, 1);

