"""Wire types crossing service boundaries.

Two submodules:
- `agent`: agent-only types (SSE frames, claim shapes, gate verdicts).
  Hand-written here as the Python source of truth. Phase I.6 generates
  the matching frontend TypeScript via `json-schema-to-typescript`.
- `shared`: types Rust + Python both use. Auto-generated by
  `just regen-wire-types` from `backend/src/wire/shared.rs`. Do NOT
  hand-edit the `shared/` directory.

Top-level re-exports below cover the agent-only frames so callers can
write `from agent_service.wire import Claim` without diving into the
submodule layout.
"""

from __future__ import annotations

from .agent import (
    AgentDone,
    AgentRequest,
    AgentSessionStarted,
    AgentSwitches,
    ChangedSince,
    Claim,
    ClaimKind,  # re-exported from wire.shared
    ConstitutionVerdict,
    CostClass,
    CrossCheckSwitches,
    DataSource,
    Delta,
    EdgeSummary,
    EntityRef,
    EntityRefCommunity,
    EntityRefEdge,
    EntityRefWallet,
    Error,
    FieldChange,
    FieldChangeCountChanged,
    FieldChangeNumberMoved,
    FieldChangeSetChanged,
    FieldDelta,
    GatePath,
    LlmExtractedNumber,
    LlmExtraction,
    NarrativeRetracted,
    NarrativeWithRefs,
    NodeSummary,
    NoMovement,
    NumberRef,  # re-exported from wire.shared
    PathState,
    PathStateApproved,
    PathStateNotApplicable,
    PathStateRetracted,
    PathStep,
    PolicyVerdict,
    PolicyVerdictApproved,
    PolicyVerdictRetracted,
    Progress,
    StubMarker,
    TimeRangeWire,
    ViewContext,
)

__all__ = [
    "AgentDone",
    "AgentRequest",
    "AgentSessionStarted",
    "AgentSwitches",
    "ChangedSince",
    "Claim",
    "ClaimKind",
    "ConstitutionVerdict",
    "CostClass",
    "CrossCheckSwitches",
    "DataSource",
    "Delta",
    "EdgeSummary",
    "EntityRef",
    "EntityRefCommunity",
    "EntityRefEdge",
    "EntityRefWallet",
    "Error",
    "FieldChange",
    "FieldChangeCountChanged",
    "FieldChangeNumberMoved",
    "FieldChangeSetChanged",
    "FieldDelta",
    "GatePath",
    "LlmExtractedNumber",
    "LlmExtraction",
    "NarrativeRetracted",
    "NarrativeWithRefs",
    "NodeSummary",
    "NoMovement",
    "NumberRef",
    "PathState",
    "PathStateApproved",
    "PathStateNotApplicable",
    "PathStateRetracted",
    "PathStep",
    "PolicyVerdict",
    "PolicyVerdictApproved",
    "PolicyVerdictRetracted",
    "Progress",
    "StubMarker",
    "TimeRangeWire",
    "ViewContext",
]
