"""Wire types crossing service boundaries.

Two submodules:
- `agent`: agent-only types (SSE frames, claim shapes). Hand-written
  in Phase 0/A; replaced by codegen from pydantic source in Phase B.2.
- `shared`: types Rust + Python both use. Auto-generated by
  `just regen-wire-types` from `backend/src/wire/shared.rs`. Do NOT
  hand-edit the `shared/` directory.

Top-level re-exports below cover the agent-only frames so callers can
write `from agent_service.wire import Claim` without diving into the
submodule layout.
"""

from __future__ import annotations

from .agent import (
    AgentDone,
    AgentRequest,
    AgentSessionStarted,
    Claim,
    Done,
)

__all__ = [
    "AgentDone",
    "AgentRequest",
    "AgentSessionStarted",
    "Claim",
    "Done",
]
