# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multichain/wire/shared/v1/get_token_info.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'multichain/wire/shared/v1/get_token_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.multichain/wire/shared/v1/get_token_info.proto\x12\x19multichain.wire.shared.v1\"\'\n\x11GetTokenInfoInput\x12\x12\n\x04mint\x18\x01 \x01(\tR\x04mint\"\x95\x02\n\x12GetTokenInfoOutput\x12\x12\n\x04mint\x18\x01 \x01(\tR\x04mint\x12\x17\n\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n\x06symbol\x18\x03 \x01(\tH\x01R\x06symbol\x88\x01\x01\x12\x15\n\x03uri\x18\x04 \x01(\tH\x02R\x03uri\x88\x01\x01\x12.\n\x10update_authority\x18\x05 \x01(\tH\x03R\x0fupdateAuthority\x88\x01\x01\x12%\n\x0esource_program\x18\x06 \x01(\tR\rsourceProgram\x12\x16\n\x06\x63\x61\x63hed\x18\x07 \x01(\x08R\x06\x63\x61\x63hedB\x07\n\x05_nameB\t\n\x07_symbolB\x06\n\x04_uriB\x13\n\x11_update_authorityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multichain.wire.shared.v1.get_token_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTOKENINFOINPUT']._serialized_start=77
  _globals['_GETTOKENINFOINPUT']._serialized_end=116
  _globals['_GETTOKENINFOOUTPUT']._serialized_start=119
  _globals['_GETTOKENINFOOUTPUT']._serialized_end=396
# @@protoc_insertion_point(module_scope)
