# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multichain/wire/shared/v1/provenance.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'multichain/wire/shared/v1/provenance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*multichain/wire/shared/v1/provenance.proto\x12\x19multichain.wire.shared.v1\"\xe3\x02\n\rProvenanceRef\x12>\n\x06wallet\x18\x01 \x01(\x0b\x32$.multichain.wire.shared.v1.WalletRefH\x00R\x06wallet\x12\x38\n\x04\x65\x64ge\x18\x02 \x01(\x0b\x32\".multichain.wire.shared.v1.EdgeRefH\x00R\x04\x65\x64ge\x12G\n\tcommunity\x18\x03 \x01(\x0b\x32\'.multichain.wire.shared.v1.CommunityRefH\x00R\tcommunity\x12H\n\ntime_range\x18\x04 \x01(\x0b\x32\'.multichain.wire.shared.v1.TimeRangeRefH\x00R\ttimeRange\x12>\n\x06number\x18\x05 \x01(\x0b\x32$.multichain.wire.shared.v1.NumberRefH\x00R\x06numberB\x05\n\x03ref\">\n\tWalletRef\x12\x12\n\x04\x61\x64\x64r\x18\x01 \x01(\tR\x04\x61\x64\x64r\x12\x15\n\x03idx\x18\x02 \x01(\rH\x00R\x03idx\x88\x01\x01\x42\x06\n\x04_idx\"=\n\x07\x45\x64geRef\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n\x03src\x18\x02 \x01(\rR\x03src\x12\x10\n\x03\x64st\x18\x03 \x01(\rR\x03\x64st\"\x1e\n\x0c\x43ommunityRef\x12\x0e\n\x02id\x18\x01 \x01(\rR\x02id\"8\n\x0cTimeRangeRef\x12\x15\n\x06\x66rom_s\x18\x01 \x01(\rR\x05\x66romS\x12\x11\n\x04to_s\x18\x02 \x01(\rR\x03toS\"S\n\tNumberRef\x12\x16\n\x06metric\x18\x01 \x01(\tR\x06metric\x12\x14\n\x05value\x18\x02 \x01(\x01R\x05value\x12\x18\n\x07support\x18\x03 \x03(\tR\x07supportb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multichain.wire.shared.v1.provenance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROVENANCEREF']._serialized_start=74
  _globals['_PROVENANCEREF']._serialized_end=429
  _globals['_WALLETREF']._serialized_start=431
  _globals['_WALLETREF']._serialized_end=493
  _globals['_EDGEREF']._serialized_start=495
  _globals['_EDGEREF']._serialized_end=556
  _globals['_COMMUNITYREF']._serialized_start=558
  _globals['_COMMUNITYREF']._serialized_end=588
  _globals['_TIMERANGEREF']._serialized_start=590
  _globals['_TIMERANGEREF']._serialized_end=646
  _globals['_NUMBERREF']._serialized_start=648
  _globals['_NUMBERREF']._serialized_end=731
# @@protoc_insertion_point(module_scope)
