# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multichain/wire/shared/v1/role.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'multichain/wire/shared/v1/role.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$multichain/wire/shared/v1/role.proto\x12\x19multichain.wire.shared.v1*\x82\x02\n\x08NodeRole\x12\x19\n\x15NODE_ROLE_UNSPECIFIED\x10\x00\x12\x18\n\x14NODE_ROLE_TOKEN_MINT\x10\x01\x12\x19\n\x15NODE_ROLE_TIP_ACCOUNT\x10\x02\x12\x1a\n\x16NODE_ROLE_MEV_SEARCHER\x10\x03\x12\x17\n\x13NODE_ROLE_MULTI_HUB\x10\x04\x12\x15\n\x11NODE_ROLE_SOL_HUB\x10\x05\x12\x15\n\x11NODE_ROLE_SPL_HUB\x10\x06\x12\x13\n\x0fNODE_ROLE_WHALE\x10\x07\x12\x18\n\x14NODE_ROLE_MPC_MEMBER\x10\x08\x12\x14\n\x10NODE_ROLE_NORMAL\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multichain.wire.shared.v1.role_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODEROLE']._serialized_start=68
  _globals['_NODEROLE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
