# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multichain/wire/shared/v1/scope.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'multichain/wire/shared/v1/scope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%multichain/wire/shared/v1/scope.proto\x12\x19multichain.wire.shared.v1\"\x8f\x01\n\tTimeScope\x12:\n\x04live\x18\x01 \x01(\x0b\x32$.multichain.wire.shared.v1.LiveScopeH\x00R\x04live\x12=\n\x05range\x18\x02 \x01(\x0b\x32%.multichain.wire.shared.v1.RangeScopeH\x00R\x05rangeB\x07\n\x05scope\"\x0b\n\tLiveScope\"6\n\nRangeScope\x12\x15\n\x06\x66rom_s\x18\x01 \x01(\rR\x05\x66romS\x12\x11\n\x04to_s\x18\x02 \x01(\rR\x03toS*p\n\tCostClass\x12\x1a\n\x16\x43OST_CLASS_UNSPECIFIED\x10\x00\x12\x14\n\x10\x43OST_CLASS_CHEAP\x10\x01\x12\x17\n\x13\x43OST_CLASS_MODERATE\x10\x02\x12\x18\n\x14\x43OST_CLASS_EXPENSIVE\x10\x03*t\n\nDataSource\x12\x1b\n\x17\x44\x41TA_SOURCE_UNSPECIFIED\x10\x00\x12\x14\n\x10\x44\x41TA_SOURCE_LIVE\x10\x01\x12\x19\n\x15\x44\x41TA_SOURCE_WAREHOUSE\x10\x02\x12\x18\n\x14\x44\x41TA_SOURCE_EXTERNAL\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multichain.wire.shared.v1.scope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COSTCLASS']._serialized_start=283
  _globals['_COSTCLASS']._serialized_end=395
  _globals['_DATASOURCE']._serialized_start=397
  _globals['_DATASOURCE']._serialized_end=513
  _globals['_TIMESCOPE']._serialized_start=69
  _globals['_TIMESCOPE']._serialized_end=212
  _globals['_LIVESCOPE']._serialized_start=214
  _globals['_LIVESCOPE']._serialized_end=225
  _globals['_RANGESCOPE']._serialized_start=227
  _globals['_RANGESCOPE']._serialized_end=281
# @@protoc_insertion_point(module_scope)
