# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multichain/wire/shared/v1/snapshot.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'multichain/wire/shared/v1/snapshot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(multichain/wire/shared/v1/snapshot.proto\x12\x19multichain.wire.shared.v1\"}\n\x15SnapshotBeginResponse\x12\x1f\n\x0bsnapshot_id\x18\x01 \x01(\tR\nsnapshotId\x12\"\n\rexpires_at_ms\x18\x02 \x01(\x04R\x0b\x65xpiresAtMs\x12\x1f\n\x0bwindow_secs\x18\x03 \x01(\rR\nwindowSecs\"5\n\x12SnapshotEndRequest\x12\x1f\n\x0bsnapshot_id\x18\x01 \x01(\tR\nsnapshotIdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multichain.wire.shared.v1.snapshot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SNAPSHOTBEGINRESPONSE']._serialized_start=71
  _globals['_SNAPSHOTBEGINRESPONSE']._serialized_end=196
  _globals['_SNAPSHOTENDREQUEST']._serialized_start=198
  _globals['_SNAPSHOTENDREQUEST']._serialized_end=251
# @@protoc_insertion_point(module_scope)
