# generated by datamodel-codegen:
#   filename:  ClaimKind.json

from __future__ import annotations

from enum import StrEnum


class ClaimKind(StrEnum):
    """
    Closed enum: the renderer dispatches to per-kind cards. New variants require a deliberate change. v0 only emits `Profile`; the rest exist so ships 3/5/7 fill them without later refactor.
    """

    profile = "profile"
    pattern = "pattern"
    comparison = "comparison"
    summary = "summary"
    pulse = "pulse"
