# generated by datamodel-codegen:
#   filename:  CommunitySummaryOutput.json

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class TopWallet(BaseModel):
    addr: str
    degree: conint(ge=0)
    volume: float


class CommunitySummaryOutput(BaseModel):
    community_id: conint(ge=0)
    edge_count: conint(ge=0) = Field(
        ..., description="Number of edges between community members (single-counted)."
    )
    external_volume: float = Field(
        ...,
        description="Sum of transfer-edge weights crossing the community boundary (one endpoint inside, one outside). Single-counted.",
    )
    internal_volume: float = Field(
        ...,
        description="Sum of transfer-edge weights between two community members. Single-counted (each edge contributes once).",
    )
    size: conint(ge=0) = Field(
        ...,
        description="Number of distinct wallets carrying this label in the live 60s window.",
    )
    top_wallets: list[TopWallet] = Field(
        ...,
        description="Top members by degree, capped at `TOP_K_WALLETS`. Ties broken by larger volume.",
    )
    total_volume: float = Field(
        ...,
        description="Total transfer volume touching any community member, double-counting (a member-to-member edge contributes once via each endpoint). Matches the `volume` semantics on `wallet_profile.stats`.",
    )
