# generated by datamodel-codegen:
#   filename:  CommunitySummaryInput.json
#   timestamp: 2026-05-02T23:55:40+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class TimeScope1(StrEnum):
    """
    Current rolling live window.
    """

    live = "live"


class Range(BaseModel):
    from_s: conint(ge=0)
    to_s: conint(ge=0)


class TimeScope2(BaseModel):
    """
    Absolute block-time range. Routes to warehouse path (ship-5).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    range: Range


class TimeScope(RootModel[TimeScope1 | TimeScope2]):
    root: TimeScope1 | TimeScope2 = Field(
        ...,
        description='Mandatory temporal frame for primitives that have one (per D-6). Externally tagged so `Live` serializes as the bare string `"live"` (which is what models naturally produce for unit variants) and `Range` as `{"range": {"from_s": ..., "to_s": ...}}`. The internally-tagged form was tried first and the model misinterpreted the schema, sending strings where objects were expected.',
    )


class CommunitySummaryInput(BaseModel):
    community_id: conint(ge=0) = Field(
        ...,
        description="Stable community label (`u32`). Source it from a prior `wallet_profile` response (the `community_id` field) or from the user's selection on the live graph.",
    )
    time_scope: TimeScope = Field(
        ...,
        description="Required temporal frame. v0 supports Live; Range routes to a stubbed warehouse path.",
    )
