# generated by datamodel-codegen:
#   filename:  CommunitySummaryRequest.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class TimeScope3(StrEnum):
    """
    Current rolling live window.
    """

    live = "live"


class Range(BaseModel):
    from_s: conint(ge=0)
    to_s: conint(ge=0)


class TimeScope4(BaseModel):
    """
    Absolute block-time range. Routes to warehouse path (ship-5).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    range: Range


class TimeScope(RootModel[TimeScope3 | TimeScope4]):
    root: TimeScope3 | TimeScope4 = Field(
        ...,
        description='Mandatory temporal frame for primitives that have one (per D-6). Externally tagged so `Live` serializes as the bare string `"live"` (which is what models naturally produce for unit variants) and `Range` as `{"range": {"from_s": ..., "to_s": ...}}`. The internally-tagged form was tried first and the model misinterpreted the schema, sending strings where objects were expected.',
    )


class CommunitySummaryInput(BaseModel):
    community_id: conint(ge=0) = Field(
        ...,
        description="Stable community label (`u32`). Source it from a prior `wallet_profile` response (the `community_id` field) or from the user's selection on the live graph.",
    )
    time_scope: TimeScope = Field(
        ...,
        description="Required temporal frame. v0 supports Live; Range routes to a stubbed warehouse path.",
    )


class CommunitySummaryRequest(BaseModel):
    """
    Body of `POST /primitive/community_summary`. Same envelope shape as `WalletProfileRequest`.
    """

    input: CommunitySummaryInput
    snapshot_id: str
