# generated by datamodel-codegen:
#   filename:  EmitClaimOutput.json

from __future__ import annotations

from pydantic import BaseModel


class EmitClaimOutput(BaseModel):
    claim_id: str
    policy: str
