# generated by datamodel-codegen:
#   filename:  EmitClaimInput.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field, RootModel, conint


class ClaimKind(StrEnum):
    """
    Closed enum: the renderer dispatches to per-kind cards. New variants require a deliberate change. v0 only emits `Profile`; the rest exist so ships 3/5/7 fill them without later refactor.
    """

    profile = "profile"
    pattern = "pattern"
    comparison = "comparison"
    summary = "summary"
    pulse = "pulse"


class EdgeSummary(BaseModel):
    dst: str
    src: str
    volume: float


class NodeSummary(BaseModel):
    addr: str
    role: str | None = None


class NumberRef(BaseModel):
    metric: str
    value: float


class Kind(StrEnum):
    wallet = "wallet"


class ProvenanceRef1(BaseModel):
    """
    `idx` is None when the wallet is not in the current live window (route to subgraph modal instead of live-graph chip).
    """

    addr: str
    idx: conint(ge=0) | None = None
    kind: Kind


class Kind1(StrEnum):
    edge = "edge"


class ProvenanceRef2(BaseModel):
    """
    Stable id format: `"<edge_idx>:<gen>"`.
    """

    dst: conint(ge=0)
    id: str
    kind: Kind1
    src: conint(ge=0)


class Kind2(StrEnum):
    community = "community"


class ProvenanceRef3(BaseModel):
    """
    Tagged reference back to a graph entity. The frontend's render-surface derivation picks live highlight, modal, or inline chip based on the ref shape (see plan: "Frontend render-surface derivation rule").
    """

    id: conint(ge=0)
    kind: Kind2


class Kind3(StrEnum):
    time_range = "time-range"


class ProvenanceRef4(BaseModel):
    """
    Populated by ship-5 warehouse primitives.
    """

    from_s: conint(ge=0)
    kind: Kind3
    to_s: conint(ge=0)


class Kind4(StrEnum):
    number = "number"


class ProvenanceRef5(BaseModel):
    """
    Aggregate metric reference. `support` lists EdgeIds backing the number so the user can drill in.
    """

    kind: Kind4
    metric: str
    support: list[str]
    value: float


class ProvenanceRef(
    RootModel[
        ProvenanceRef1
        | ProvenanceRef2
        | ProvenanceRef3
        | ProvenanceRef4
        | ProvenanceRef5
    ]
):
    root: (
        ProvenanceRef1
        | ProvenanceRef2
        | ProvenanceRef3
        | ProvenanceRef4
        | ProvenanceRef5
    ) = Field(
        ...,
        description='Tagged reference back to a graph entity. The frontend\'s render-surface derivation picks live highlight, modal, or inline chip based on the ref shape (see plan: "Frontend render-surface derivation rule").',
    )


class TimeRangeWire(BaseModel):
    from_s: conint(ge=0)
    to_s: conint(ge=0)


class SubgraphSlice(BaseModel):
    """
    Self-contained subgraph rendered on its own canvas in a modal. Used by ship-5 for historical results that don't share layout state with the live graph.
    """

    edges: list[EdgeSummary]
    nodes: list[NodeSummary]
    time_range: TimeRangeWire | None = None


class EmitClaimInput(BaseModel):
    """
    Input shape the model sends. Matches `Claim` minus the runtime- stamped fields (`id`, `session_id`, `emitted_at_ms`, `policy_verdict`, `stubs_active`, which are runtime-controlled).
    """

    body_markdown: str
    headline: str
    kind: ClaimKind
    provenance: list[ProvenanceRef]
    subgraph_slice: SubgraphSlice | None = None
    support_numbers: list[NumberRef] | None = Field([], validate_default=True)
