# generated by datamodel-codegen:
#   filename:  NodeRole.json

from __future__ import annotations

from enum import StrEnum


class NodeRole(StrEnum):
    """
    Wire-stable per-node role tag. Kebab-case strings on the wire so the frontend's existing union type (`"token-mint" | "tip-account" | ...`) reads them unchanged.
    """

    token_mint = "token-mint"
    tip_account = "tip-account"
    mev_searcher = "mev-searcher"
    multi_hub = "multi-hub"
    sol_hub = "sol-hub"
    spl_hub = "spl-hub"
    whale = "whale"
    mpc_member = "mpc-member"
    normal = "normal"
