# generated by datamodel-codegen:
#   filename:  PrimitiveResponseEnvelope.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field, RootModel, conint


class EdgeSummary(BaseModel):
    dst: str
    src: str
    volume: float


class NodeSummary(BaseModel):
    addr: str
    role: str | None = None


class Kind(StrEnum):
    wallet = "wallet"


class ProvenanceRef6(BaseModel):
    """
    `idx` is None when the wallet is not in the current live window (route to subgraph modal instead of live-graph chip).
    """

    addr: str
    idx: conint(ge=0) | None = None
    kind: Kind


class Kind6(StrEnum):
    edge = "edge"


class ProvenanceRef7(BaseModel):
    """
    Stable id format: `"<edge_idx>:<gen>"`.
    """

    dst: conint(ge=0)
    id: str
    kind: Kind6
    src: conint(ge=0)


class Kind7(StrEnum):
    community = "community"


class ProvenanceRef8(BaseModel):
    """
    Tagged reference back to a graph entity. The frontend's render-surface derivation picks live highlight, modal, or inline chip based on the ref shape (see plan: "Frontend render-surface derivation rule").
    """

    id: conint(ge=0)
    kind: Kind7


class Kind8(StrEnum):
    time_range = "time-range"


class ProvenanceRef9(BaseModel):
    """
    Populated by ship-5 warehouse primitives.
    """

    from_s: conint(ge=0)
    kind: Kind8
    to_s: conint(ge=0)


class Kind9(StrEnum):
    number = "number"


class ProvenanceRef10(BaseModel):
    """
    Aggregate metric reference. `support` lists EdgeIds backing the number so the user can drill in.
    """

    kind: Kind9
    metric: str
    support: list[str]
    value: float


class ProvenanceRef(
    RootModel[
        ProvenanceRef6
        | ProvenanceRef7
        | ProvenanceRef8
        | ProvenanceRef9
        | ProvenanceRef10
    ]
):
    root: (
        ProvenanceRef6
        | ProvenanceRef7
        | ProvenanceRef8
        | ProvenanceRef9
        | ProvenanceRef10
    ) = Field(
        ...,
        description='Tagged reference back to a graph entity. The frontend\'s render-surface derivation picks live highlight, modal, or inline chip based on the ref shape (see plan: "Frontend render-surface derivation rule").',
    )


class TimeRangeWire(BaseModel):
    from_s: conint(ge=0)
    to_s: conint(ge=0)


class SubgraphSlice(BaseModel):
    """
    Self-contained subgraph rendered on its own canvas in a modal. Used by ship-5 for historical results that don't share layout state with the live graph.
    """

    edges: list[EdgeSummary]
    nodes: list[NodeSummary]
    time_range: TimeRangeWire | None = None


class PrimitiveResponseEnvelope(BaseModel):
    """
    Generic primitive response envelope. Mirrors `PrimitiveOutput<T>` from the existing primitive trait but flattened for the wire so Python doesn't need to learn about the Rust generic.

    `value` is intentionally `serde_json::Value` here in the Rust shape so this single envelope can wrap any primitive's output. The Python client typed-validates `value` against the matching per-primitive output model.
    """

    provenance: list[ProvenanceRef]
    subgraph_slice: SubgraphSlice | None = None
    value: Any
