# generated by datamodel-codegen:
#   filename:  ProvenanceRef.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field, RootModel, conint


class Kind(StrEnum):
    wallet = "wallet"


class ProvenanceRef11(BaseModel):
    """
    `idx` is None when the wallet is not in the current live window (route to subgraph modal instead of live-graph chip).
    """

    addr: str
    idx: conint(ge=0) | None = None
    kind: Kind


class Kind11(StrEnum):
    edge = "edge"


class ProvenanceRef12(BaseModel):
    """
    Stable id format: `"<edge_idx>:<gen>"`.
    """

    dst: conint(ge=0)
    id: str
    kind: Kind11
    src: conint(ge=0)


class Kind12(StrEnum):
    community = "community"


class ProvenanceRef13(BaseModel):
    """
    Tagged reference back to a graph entity. The frontend's render-surface derivation picks live highlight, modal, or inline chip based on the ref shape (see plan: "Frontend render-surface derivation rule").
    """

    id: conint(ge=0)
    kind: Kind12


class Kind13(StrEnum):
    time_range = "time-range"


class ProvenanceRef14(BaseModel):
    """
    Populated by ship-5 warehouse primitives.
    """

    from_s: conint(ge=0)
    kind: Kind13
    to_s: conint(ge=0)


class Kind14(StrEnum):
    number = "number"


class ProvenanceRef15(BaseModel):
    """
    Aggregate metric reference. `support` lists EdgeIds backing the number so the user can drill in.
    """

    kind: Kind14
    metric: str
    support: list[str]
    value: float


class ProvenanceRef(
    RootModel[
        ProvenanceRef11
        | ProvenanceRef12
        | ProvenanceRef13
        | ProvenanceRef14
        | ProvenanceRef15
    ]
):
    root: (
        ProvenanceRef11
        | ProvenanceRef12
        | ProvenanceRef13
        | ProvenanceRef14
        | ProvenanceRef15
    ) = Field(
        ...,
        description='Tagged reference back to a graph entity. The frontend\'s render-surface derivation picks live highlight, modal, or inline chip based on the ref shape (see plan: "Frontend render-surface derivation rule").',
        title="ProvenanceRef",
    )
