# generated by datamodel-codegen:
#   filename:  ProvenanceRef.json
#   timestamp: 2026-05-02T23:55:40+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field, RootModel, conint


class Kind(StrEnum):
    wallet = "wallet"


class ProvenanceRef6(BaseModel):
    """
    `idx` is None when the wallet is not in the current live window (route to subgraph modal instead of live-graph chip).
    """

    addr: str
    idx: conint(ge=0) | None = None
    kind: Kind


class Kind6(StrEnum):
    edge = "edge"


class ProvenanceRef7(BaseModel):
    """
    Stable id format: `"<edge_idx>:<gen>"`.
    """

    dst: conint(ge=0)
    id: str
    kind: Kind6
    src: conint(ge=0)


class Kind7(StrEnum):
    community = "community"


class ProvenanceRef8(BaseModel):
    """
    Tagged reference back to a graph entity. The frontend's render-surface derivation picks live highlight, modal, or inline chip based on the ref shape (see plan: "Frontend render-surface derivation rule").
    """

    id: conint(ge=0)
    kind: Kind7


class Kind8(StrEnum):
    time_range = "time-range"


class ProvenanceRef9(BaseModel):
    """
    Populated by ship-5 warehouse primitives.
    """

    from_s: conint(ge=0)
    kind: Kind8
    to_s: conint(ge=0)


class Kind9(StrEnum):
    number = "number"


class ProvenanceRef10(BaseModel):
    """
    Aggregate metric reference. `support` lists EdgeIds backing the number so the user can drill in.
    """

    kind: Kind9
    metric: str
    support: list[str]
    value: float


class ProvenanceRef(
    RootModel[
        ProvenanceRef6
        | ProvenanceRef7
        | ProvenanceRef8
        | ProvenanceRef9
        | ProvenanceRef10
    ]
):
    root: (
        ProvenanceRef6
        | ProvenanceRef7
        | ProvenanceRef8
        | ProvenanceRef9
        | ProvenanceRef10
    ) = Field(
        ...,
        description='Tagged reference back to a graph entity. The frontend\'s render-surface derivation picks live highlight, modal, or inline chip based on the ref shape (see plan: "Frontend render-surface derivation rule").',
        title="ProvenanceRef",
    )
