# generated by datamodel-codegen:
#   filename:  SnapshotEndRequest.json

from __future__ import annotations

from pydantic import BaseModel


class SnapshotEndRequest(BaseModel):
    """
    Body of `POST /turn/end`. Releases the snapshot eagerly. Optional; the GC sweep would clean it up within 5 minutes anyway, but eager release keeps the cache small for healthy turns.
    """

    snapshot_id: str
