# generated by datamodel-codegen:
#   filename:  SnapshotBeginResponse.json

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class SnapshotBeginResponse(BaseModel):
    """
    Response from `POST /turn/begin`. The Python agent stashes the `snapshot_id` and passes it on every subsequent primitive call in the same turn so reads are consistent across primitives even if new blocks ingest mid-turn.

    `expires_at_ms` is a wallclock floor; the actual GC sweep on the Rust side may keep the snapshot slightly longer. After this time the Python client must re-`/turn/begin`.
    """

    expires_at_ms: conint(ge=0)
    snapshot_id: str
    window_secs: conint(ge=0) = Field(
        ...,
        description="The window the snapshot was materialized at (matches the agent's live window). Phase A only supports 60s; future ships may add a `window_secs` field on the begin request to negotiate.",
    )
