# generated by datamodel-codegen:
#   filename:  SubgraphSlice.json

from __future__ import annotations

from pydantic import BaseModel, conint


class EdgeSummary(BaseModel):
    dst: str
    src: str
    volume: float


class NodeSummary(BaseModel):
    addr: str
    role: str | None = None


class TimeRangeWire(BaseModel):
    from_s: conint(ge=0)
    to_s: conint(ge=0)


class SubgraphSlice(BaseModel):
    """
    Self-contained subgraph rendered on its own canvas in a modal. Used by ship-5 for historical results that don't share layout state with the live graph.
    """

    edges: list[EdgeSummary]
    nodes: list[NodeSummary]
    time_range: TimeRangeWire | None = None
