# generated by datamodel-codegen:
#   filename:  TimeScope.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class TimeScope5(StrEnum):
    """
    Current rolling live window.
    """

    live = "live"


class Range(BaseModel):
    from_s: conint(ge=0)
    to_s: conint(ge=0)


class TimeScope6(BaseModel):
    """
    Absolute block-time range. Routes to warehouse path (ship-5).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    range: Range


class TimeScope(RootModel[TimeScope5 | TimeScope6]):
    root: TimeScope5 | TimeScope6 = Field(
        ...,
        description='Mandatory temporal frame for primitives that have one (per D-6). Externally tagged so `Live` serializes as the bare string `"live"` (which is what models naturally produce for unit variants) and `Range` as `{"range": {"from_s": ..., "to_s": ...}}`. The internally-tagged form was tried first and the model misinterpreted the schema, sending strings where objects were expected.',
        title="TimeScope",
    )
