# generated by datamodel-codegen:
#   filename:  TopCounterparty.json
#   timestamp: 2026-05-02T23:55:40+00:00

from __future__ import annotations

from pydantic import BaseModel


class TopCounterparty(BaseModel):
    addr: str
    volume: float
