# generated by datamodel-codegen:
#   filename:  TopCounterparty.json

from __future__ import annotations

from pydantic import BaseModel


class TopCounterparty(BaseModel):
    addr: str
    volume: float
