# generated by datamodel-codegen:
#   filename:  TopWallet.json
#   timestamp: 2026-05-02T23:55:40+00:00

from __future__ import annotations

from pydantic import BaseModel, conint


class TopWallet(BaseModel):
    addr: str
    degree: conint(ge=0)
    volume: float
