# generated by datamodel-codegen:
#   filename:  TopWallet.json

from __future__ import annotations

from pydantic import BaseModel, conint


class TopWallet(BaseModel):
    addr: str
    degree: conint(ge=0)
    volume: float
