# generated by datamodel-codegen:
#   filename:  WalletProfileRequest.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class TimeScope(StrEnum):
    """
    Current rolling live window.
    """

    live = "live"


class Range(BaseModel):
    from_s: conint(ge=0)
    to_s: conint(ge=0)


class TimeScope11(BaseModel):
    """
    Absolute block-time range. Routes to warehouse path (ship-5).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    range: Range


class TimeScope9(RootModel[TimeScope | TimeScope11]):
    root: TimeScope | TimeScope11 = Field(
        ...,
        description='Mandatory temporal frame for primitives that have one (per D-6). Externally tagged so `Live` serializes as the bare string `"live"` (which is what models naturally produce for unit variants) and `Range` as `{"range": {"from_s": ..., "to_s": ...}}`. The internally-tagged form was tried first and the model misinterpreted the schema, sending strings where objects were expected.',
    )


class WalletProfileInput(BaseModel):
    addr: str = Field(..., description="Wallet pubkey (base58 Solana address).")
    time_scope: TimeScope9 = Field(
        ...,
        description="Required temporal frame. v0 supports Live; Range routes to a stubbed warehouse path.",
    )


class WalletProfileRequest(BaseModel):
    """
    Body of `POST /primitive/wallet_profile`. Wraps the existing `WalletProfileInput` with the snapshot lease so the route is addressable from Python without ambient state.
    """

    input: WalletProfileInput
    snapshot_id: str
