// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file multichain/wire/shared/v1/community_summary.proto (package multichain.wire.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { TimeScope } from "./scope_pb.js";
import { file_multichain_wire_shared_v1_scope } from "./scope_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/shared/v1/community_summary.proto.
 */
export const file_multichain_wire_shared_v1_community_summary: GenFile = /*@__PURE__*/
  fileDesc("CjFtdWx0aWNoYWluL3dpcmUvc2hhcmVkL3YxL2NvbW11bml0eV9zdW1tYXJ5LnByb3RvEhltdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxImcKFUNvbW11bml0eVN1bW1hcnlJbnB1dBIUCgxjb21tdW5pdHlfaWQYASABKA0SOAoKdGltZV9zY29wZRgCIAEoCzIkLm11bHRpY2hhaW4ud2lyZS5zaGFyZWQudjEuVGltZVNjb3BlItMBChZDb21tdW5pdHlTdW1tYXJ5T3V0cHV0EhQKDGNvbW11bml0eV9pZBgBIAEoDRIMCgRzaXplGAIgASgNEhQKDHRvdGFsX3ZvbHVtZRgDIAEoARIXCg9pbnRlcm5hbF92b2x1bWUYBCABKAESFwoPZXh0ZXJuYWxfdm9sdW1lGAUgASgBEhIKCmVkZ2VfY291bnQYBiABKA0SOQoLdG9wX3dhbGxldHMYByADKAsyJC5tdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxLlRvcFdhbGxldCI5CglUb3BXYWxsZXQSDAoEYWRkchgBIAEoCRIOCgZkZWdyZWUYAiABKA0SDgoGdm9sdW1lGAMgASgBYgZwcm90bzM", [file_multichain_wire_shared_v1_scope]);

/**
 * Input to the `community_summary` primitive.
 *
 * @generated from message multichain.wire.shared.v1.CommunitySummaryInput
 */
export type CommunitySummaryInput = Message<"multichain.wire.shared.v1.CommunitySummaryInput"> & {
  /**
   * @generated from field: uint32 community_id = 1;
   */
  communityId: number;

  /**
   * @generated from field: multichain.wire.shared.v1.TimeScope time_scope = 2;
   */
  timeScope?: TimeScope | undefined;
};

/**
 * Describes the message multichain.wire.shared.v1.CommunitySummaryInput.
 * Use `create(CommunitySummaryInputSchema)` to create a new message.
 */
export const CommunitySummaryInputSchema: GenMessage<CommunitySummaryInput> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_community_summary, 0);

/**
 * Output of the `community_summary` primitive. The agent reads this
 * to build the community-context claim.
 *
 * @generated from message multichain.wire.shared.v1.CommunitySummaryOutput
 */
export type CommunitySummaryOutput = Message<"multichain.wire.shared.v1.CommunitySummaryOutput"> & {
  /**
   * @generated from field: uint32 community_id = 1;
   */
  communityId: number;

  /**
   * Number of wallets in the community within the current scope.
   *
   * @generated from field: uint32 size = 2;
   */
  size: number;

  /**
   * Sum of all internal + external edge volumes (lamports).
   *
   * @generated from field: double total_volume = 3;
   */
  totalVolume: number;

  /**
   * Edge volume strictly within the community (lamports).
   *
   * @generated from field: double internal_volume = 4;
   */
  internalVolume: number;

  /**
   * Edge volume crossing community boundary (lamports).
   *
   * @generated from field: double external_volume = 5;
   */
  externalVolume: number;

  /**
   * @generated from field: uint32 edge_count = 6;
   */
  edgeCount: number;

  /**
   * Capped at K (impl-defined, currently 5).
   *
   * @generated from field: repeated multichain.wire.shared.v1.TopWallet top_wallets = 7;
   */
  topWallets: TopWallet[];
};

/**
 * Describes the message multichain.wire.shared.v1.CommunitySummaryOutput.
 * Use `create(CommunitySummaryOutputSchema)` to create a new message.
 */
export const CommunitySummaryOutputSchema: GenMessage<CommunitySummaryOutput> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_community_summary, 1);

/**
 * @generated from message multichain.wire.shared.v1.TopWallet
 */
export type TopWallet = Message<"multichain.wire.shared.v1.TopWallet"> & {
  /**
   * @generated from field: string addr = 1;
   */
  addr: string;

  /**
   * @generated from field: uint32 degree = 2;
   */
  degree: number;

  /**
   * Lamports.
   *
   * @generated from field: double volume = 3;
   */
  volume: number;
};

/**
 * Describes the message multichain.wire.shared.v1.TopWallet.
 * Use `create(TopWalletSchema)` to create a new message.
 */
export const TopWalletSchema: GenMessage<TopWallet> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_community_summary, 2);

