// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file multichain/wire/shared/v1/get_token_info.proto (package multichain.wire.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/shared/v1/get_token_info.proto.
 */
export const file_multichain_wire_shared_v1_get_token_info: GenFile = /*@__PURE__*/
  fileDesc("Ci5tdWx0aWNoYWluL3dpcmUvc2hhcmVkL3YxL2dldF90b2tlbl9pbmZvLnByb3RvEhltdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxIiEKEUdldFRva2VuSW5mb0lucHV0EgwKBG1pbnQYASABKAki1AEKEkdldFRva2VuSW5mb091dHB1dBIMCgRtaW50GAEgASgJEhEKBG5hbWUYAiABKAlIAIgBARITCgZzeW1ib2wYAyABKAlIAYgBARIQCgN1cmkYBCABKAlIAogBARIdChB1cGRhdGVfYXV0aG9yaXR5GAUgASgJSAOIAQESFgoOc291cmNlX3Byb2dyYW0YBiABKAkSDgoGY2FjaGVkGAcgASgIQgcKBV9uYW1lQgkKB19zeW1ib2xCBgoEX3VyaUITChFfdXBkYXRlX2F1dGhvcml0eWIGcHJvdG8z");

/**
 * Input to the `get_token_info` primitive. Resolves a Solana mint
 * pubkey to its on-chain `name / symbol / uri` via the lazy-fetch path
 * in `backend::metadata::fetch`. The primitive is stateless (does not
 * depend on the per-turn 60-second window snapshot) so the request
 * envelope's `snapshot_id` is carried for parallelism with other
 * primitives but ignored by the handler.
 *
 * @generated from message multichain.wire.shared.v1.GetTokenInfoInput
 */
export type GetTokenInfoInput = Message<"multichain.wire.shared.v1.GetTokenInfoInput"> & {
  /**
   * base58 mint pubkey. Both legacy SPL Token mints (Metaplex PDA
   * path) and SPL Token-2022 mints with the metadata extension are
   * accepted.
   *
   * @generated from field: string mint = 1;
   */
  mint: string;
};

/**
 * Describes the message multichain.wire.shared.v1.GetTokenInfoInput.
 * Use `create(GetTokenInfoInputSchema)` to create a new message.
 */
export const GetTokenInfoInputSchema: GenMessage<GetTokenInfoInput> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_get_token_info, 0);

/**
 * Output of the `get_token_info` primitive.
 *
 * Empty `source_program` means the mint exists on chain but has no
 * resolvable metadata via either Metaplex PDA or Token-2022 inline
 * extension. Callers should treat this as "no metadata available"
 * rather than an error.
 *
 * All string fields except `source_program` are `optional` because
 * the same shape carries both "found" and "not found" results: when
 * not found, the four metadata fields are absent and `source_program`
 * is empty.
 *
 * @generated from message multichain.wire.shared.v1.GetTokenInfoOutput
 */
export type GetTokenInfoOutput = Message<"multichain.wire.shared.v1.GetTokenInfoOutput"> & {
  /**
   * base58 mint pubkey, echoed for caller convenience.
   *
   * @generated from field: string mint = 1;
   */
  mint: string;

  /**
   * Token name. Untrusted text chosen by the mint creator at issue
   * time. Wrap in `<external_data>` per agent-service convention
   * before surfacing to the model.
   *
   * @generated from field: optional string name = 2;
   */
  name?: string | undefined;

  /**
   * Token symbol. Same untrusted-text caveat as `name`.
   *
   * @generated from field: optional string symbol = 3;
   */
  symbol?: string | undefined;

  /**
   * URI pointing to off-chain JSON (image, description, etc.).
   * Off-chain fetch is a separate primitive; this field is the raw
   * string from the on-chain account.
   *
   * @generated from field: optional string uri = 4;
   */
  uri?: string | undefined;

  /**
   * base58 pubkey of the account authorized to update this metadata.
   * Useful for the agent narrating "the token issuer can still rename
   * / re-uri this" vs an immutable mint.
   *
   * @generated from field: optional string update_authority = 5;
   */
  updateAuthority?: string | undefined;

  /**
   * Provenance of the resolved metadata. One of:
   *   "metaplex"   - read from a Metaplex Token Metadata PDA
   *   "token2022"  - read from a Token-2022 metadata extension on
   *                  the mint account itself
   *   ""           - mint exists but has no resolvable metadata
   *
   * @generated from field: string source_program = 6;
   */
  sourceProgram: string;

  /**
   * true iff the response was served from the existing
   * `multichain.token_metadata` ClickHouse row (no RPC call this
   * request); false when this request triggered a fresh fetch and
   * wrote the row.
   *
   * @generated from field: bool cached = 7;
   */
  cached: boolean;
};

/**
 * Describes the message multichain.wire.shared.v1.GetTokenInfoOutput.
 * Use `create(GetTokenInfoOutputSchema)` to create a new message.
 */
export const GetTokenInfoOutputSchema: GenMessage<GetTokenInfoOutput> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_get_token_info, 1);

