// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file multichain/wire/shared/v1/primitive_envelope.proto (package multichain.wire.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { CommunitySummaryInput } from "./community_summary_pb";
import { file_multichain_wire_shared_v1_community_summary } from "./community_summary_pb";
import type { ProvenanceRef } from "./provenance_pb";
import { file_multichain_wire_shared_v1_provenance } from "./provenance_pb";
import type { SubgraphSlice } from "./subgraph_pb";
import { file_multichain_wire_shared_v1_subgraph } from "./subgraph_pb";
import type { WalletProfileInput } from "./wallet_profile_pb";
import { file_multichain_wire_shared_v1_wallet_profile } from "./wallet_profile_pb";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/shared/v1/primitive_envelope.proto.
 */
export const file_multichain_wire_shared_v1_primitive_envelope: GenFile = /*@__PURE__*/
  fileDesc("CjJtdWx0aWNoYWluL3dpcmUvc2hhcmVkL3YxL3ByaW1pdGl2ZV9lbnZlbG9wZS5wcm90bxIZbXVsdGljaGFpbi53aXJlLnNoYXJlZC52MSJpChRXYWxsZXRQcm9maWxlUmVxdWVzdBI8CgVpbnB1dBgBIAEoCzItLm11bHRpY2hhaW4ud2lyZS5zaGFyZWQudjEuV2FsbGV0UHJvZmlsZUlucHV0EhMKC3NuYXBzaG90X2lkGAIgASgJIm8KF0NvbW11bml0eVN1bW1hcnlSZXF1ZXN0Ej8KBWlucHV0GAEgASgLMjAubXVsdGljaGFpbi53aXJlLnNoYXJlZC52MS5Db21tdW5pdHlTdW1tYXJ5SW5wdXQSEwoLc25hcHNob3RfaWQYAiABKAki2wEKGVByaW1pdGl2ZVJlc3BvbnNlRW52ZWxvcGUSJgoFdmFsdWUYASABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0EjwKCnByb3ZlbmFuY2UYAiADKAsyKC5tdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxLlByb3ZlbmFuY2VSZWYSRQoOc3ViZ3JhcGhfc2xpY2UYAyABKAsyKC5tdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxLlN1YmdyYXBoU2xpY2VIAIgBAUIRCg9fc3ViZ3JhcGhfc2xpY2ViBnByb3RvMw", [file_google_protobuf_struct, file_multichain_wire_shared_v1_community_summary, file_multichain_wire_shared_v1_provenance, file_multichain_wire_shared_v1_subgraph, file_multichain_wire_shared_v1_wallet_profile]);

/**
 * Body of `POST /primitive/wallet_profile`. Wraps the WalletProfileInput
 * with the snapshot lease so the route is addressable from Python
 * without ambient state.
 *
 * @generated from message multichain.wire.shared.v1.WalletProfileRequest
 */
export type WalletProfileRequest = Message<"multichain.wire.shared.v1.WalletProfileRequest"> & {
  /**
   * @generated from field: multichain.wire.shared.v1.WalletProfileInput input = 1;
   */
  input?: WalletProfileInput | undefined;

  /**
   * @generated from field: string snapshot_id = 2;
   */
  snapshotId: string;
};

/**
 * Describes the message multichain.wire.shared.v1.WalletProfileRequest.
 * Use `create(WalletProfileRequestSchema)` to create a new message.
 */
export const WalletProfileRequestSchema: GenMessage<WalletProfileRequest> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_primitive_envelope, 0);

/**
 * Body of `POST /primitive/community_summary`. Same envelope shape
 * as WalletProfileRequest.
 *
 * @generated from message multichain.wire.shared.v1.CommunitySummaryRequest
 */
export type CommunitySummaryRequest = Message<"multichain.wire.shared.v1.CommunitySummaryRequest"> & {
  /**
   * @generated from field: multichain.wire.shared.v1.CommunitySummaryInput input = 1;
   */
  input?: CommunitySummaryInput | undefined;

  /**
   * @generated from field: string snapshot_id = 2;
   */
  snapshotId: string;
};

/**
 * Describes the message multichain.wire.shared.v1.CommunitySummaryRequest.
 * Use `create(CommunitySummaryRequestSchema)` to create a new message.
 */
export const CommunitySummaryRequestSchema: GenMessage<CommunitySummaryRequest> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_primitive_envelope, 1);

/**
 * Generic primitive response envelope. Mirrors `PrimitiveOutput<T>`
 * from the existing primitive trait but flattened for the wire so
 * Python doesn't need to learn about the Rust generic.
 *
 * `value` is `google.protobuf.Struct` (loose JSON) so this single
 * envelope can wrap any primitive's output. The Python client typed-
 * validates `value` against the matching per-primitive output message
 * after receiving it.
 *
 * @generated from message multichain.wire.shared.v1.PrimitiveResponseEnvelope
 */
export type PrimitiveResponseEnvelope = Message<"multichain.wire.shared.v1.PrimitiveResponseEnvelope"> & {
  /**
   * @generated from field: google.protobuf.Struct value = 1;
   */
  value?: JsonObject | undefined;

  /**
   * @generated from field: repeated multichain.wire.shared.v1.ProvenanceRef provenance = 2;
   */
  provenance: ProvenanceRef[];

  /**
   * @generated from field: optional multichain.wire.shared.v1.SubgraphSlice subgraph_slice = 3;
   */
  subgraphSlice?: SubgraphSlice | undefined;
};

/**
 * Describes the message multichain.wire.shared.v1.PrimitiveResponseEnvelope.
 * Use `create(PrimitiveResponseEnvelopeSchema)` to create a new message.
 */
export const PrimitiveResponseEnvelopeSchema: GenMessage<PrimitiveResponseEnvelope> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_primitive_envelope, 2);

