// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file multichain/wire/shared/v1/provenance.proto (package multichain.wire.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/shared/v1/provenance.proto.
 */
export const file_multichain_wire_shared_v1_provenance: GenFile = /*@__PURE__*/
  fileDesc("CiptdWx0aWNoYWluL3dpcmUvc2hhcmVkL3YxL3Byb3ZlbmFuY2UucHJvdG8SGW11bHRpY2hhaW4ud2lyZS5zaGFyZWQudjEitwIKDVByb3ZlbmFuY2VSZWYSNgoGd2FsbGV0GAEgASgLMiQubXVsdGljaGFpbi53aXJlLnNoYXJlZC52MS5XYWxsZXRSZWZIABIyCgRlZGdlGAIgASgLMiIubXVsdGljaGFpbi53aXJlLnNoYXJlZC52MS5FZGdlUmVmSAASPAoJY29tbXVuaXR5GAMgASgLMicubXVsdGljaGFpbi53aXJlLnNoYXJlZC52MS5Db21tdW5pdHlSZWZIABI9Cgp0aW1lX3JhbmdlGAQgASgLMicubXVsdGljaGFpbi53aXJlLnNoYXJlZC52MS5UaW1lUmFuZ2VSZWZIABI2CgZudW1iZXIYBSABKAsyJC5tdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxLk51bWJlclJlZkgAQgUKA3JlZiIzCglXYWxsZXRSZWYSDAoEYWRkchgBIAEoCRIQCgNpZHgYAiABKA1IAIgBAUIGCgRfaWR4Ii8KB0VkZ2VSZWYSCgoCaWQYASABKAkSCwoDc3JjGAIgASgNEgsKA2RzdBgDIAEoDSIaCgxDb21tdW5pdHlSZWYSCgoCaWQYASABKA0iLAoMVGltZVJhbmdlUmVmEg4KBmZyb21fcxgBIAEoDRIMCgR0b19zGAIgASgNIjsKCU51bWJlclJlZhIOCgZtZXRyaWMYASABKAkSDQoFdmFsdWUYAiABKAESDwoHc3VwcG9ydBgDIAMoCWIGcHJvdG8z");

/**
 * Tagged reference back to a graph entity. The frontend's render-surface
 * derivation picks live highlight, modal, or inline chip based on the
 * ref shape (see plan: "Frontend render-surface derivation rule").
 *
 * Wire format follows proto canonical JSON: the active oneof case becomes
 * the wrapping key.
 *
 *   wallet    -> {"wallet":    {"addr": "...", "idx": 0}}
 *   edge      -> {"edge":      {"id": "0:1", "src": 0, "dst": 1}}
 *   community -> {"community": {"id": 8}}
 *   timeRange -> {"timeRange": {"fromS": 0, "toS": 60}}
 *   number    -> {"number":    {"metric": "...", "value": 1.0, "support": [...]}}
 *
 * @generated from message multichain.wire.shared.v1.ProvenanceRef
 */
export type ProvenanceRef = Message<"multichain.wire.shared.v1.ProvenanceRef"> & {
  /**
   * @generated from oneof multichain.wire.shared.v1.ProvenanceRef.ref
   */
  ref: {
    /**
     * @generated from field: multichain.wire.shared.v1.WalletRef wallet = 1;
     */
    value: WalletRef;
    case: "wallet";
  } | {
    /**
     * @generated from field: multichain.wire.shared.v1.EdgeRef edge = 2;
     */
    value: EdgeRef;
    case: "edge";
  } | {
    /**
     * @generated from field: multichain.wire.shared.v1.CommunityRef community = 3;
     */
    value: CommunityRef;
    case: "community";
  } | {
    /**
     * @generated from field: multichain.wire.shared.v1.TimeRangeRef time_range = 4;
     */
    value: TimeRangeRef;
    case: "timeRange";
  } | {
    /**
     * @generated from field: multichain.wire.shared.v1.NumberRef number = 5;
     */
    value: NumberRef;
    case: "number";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message multichain.wire.shared.v1.ProvenanceRef.
 * Use `create(ProvenanceRefSchema)` to create a new message.
 */
export const ProvenanceRefSchema: GenMessage<ProvenanceRef> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_provenance, 0);

/**
 * @generated from message multichain.wire.shared.v1.WalletRef
 */
export type WalletRef = Message<"multichain.wire.shared.v1.WalletRef"> & {
  /**
   * @generated from field: string addr = 1;
   */
  addr: string;

  /**
   * None when the wallet is not in the current live window
   * (route to subgraph modal instead of live-graph chip).
   *
   * @generated from field: optional uint32 idx = 2;
   */
  idx?: number | undefined;
};

/**
 * Describes the message multichain.wire.shared.v1.WalletRef.
 * Use `create(WalletRefSchema)` to create a new message.
 */
export const WalletRefSchema: GenMessage<WalletRef> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_provenance, 1);

/**
 * @generated from message multichain.wire.shared.v1.EdgeRef
 */
export type EdgeRef = Message<"multichain.wire.shared.v1.EdgeRef"> & {
  /**
   * Stable id format: `"<edge_idx>:<gen>"`.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: uint32 src = 2;
   */
  src: number;

  /**
   * @generated from field: uint32 dst = 3;
   */
  dst: number;
};

/**
 * Describes the message multichain.wire.shared.v1.EdgeRef.
 * Use `create(EdgeRefSchema)` to create a new message.
 */
export const EdgeRefSchema: GenMessage<EdgeRef> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_provenance, 2);

/**
 * @generated from message multichain.wire.shared.v1.CommunityRef
 */
export type CommunityRef = Message<"multichain.wire.shared.v1.CommunityRef"> & {
  /**
   * @generated from field: uint32 id = 1;
   */
  id: number;
};

/**
 * Describes the message multichain.wire.shared.v1.CommunityRef.
 * Use `create(CommunityRefSchema)` to create a new message.
 */
export const CommunityRefSchema: GenMessage<CommunityRef> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_provenance, 3);

/**
 * Populated by ship-5 warehouse primitives.
 *
 * @generated from message multichain.wire.shared.v1.TimeRangeRef
 */
export type TimeRangeRef = Message<"multichain.wire.shared.v1.TimeRangeRef"> & {
  /**
   * @generated from field: uint32 from_s = 1;
   */
  fromS: number;

  /**
   * @generated from field: uint32 to_s = 2;
   */
  toS: number;
};

/**
 * Describes the message multichain.wire.shared.v1.TimeRangeRef.
 * Use `create(TimeRangeRefSchema)` to create a new message.
 */
export const TimeRangeRefSchema: GenMessage<TimeRangeRef> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_provenance, 4);

/**
 * Aggregate metric reference. `support` lists EdgeIds backing the
 * number so the user can drill in.
 *
 * @generated from message multichain.wire.shared.v1.NumberRef
 */
export type NumberRef = Message<"multichain.wire.shared.v1.NumberRef"> & {
  /**
   * @generated from field: string metric = 1;
   */
  metric: string;

  /**
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * @generated from field: repeated string support = 3;
   */
  support: string[];
};

/**
 * Describes the message multichain.wire.shared.v1.NumberRef.
 * Use `create(NumberRefSchema)` to create a new message.
 */
export const NumberRefSchema: GenMessage<NumberRef> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_provenance, 5);

