// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file multichain/wire/shared/v1/role.proto (package multichain.wire.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file multichain/wire/shared/v1/role.proto.
 */
export const file_multichain_wire_shared_v1_role: GenFile = /*@__PURE__*/
  fileDesc("CiRtdWx0aWNoYWluL3dpcmUvc2hhcmVkL3YxL3JvbGUucHJvdG8SGW11bHRpY2hhaW4ud2lyZS5zaGFyZWQudjEqggIKCE5vZGVSb2xlEhkKFU5PREVfUk9MRV9VTlNQRUNJRklFRBAAEhgKFE5PREVfUk9MRV9UT0tFTl9NSU5UEAESGQoVTk9ERV9ST0xFX1RJUF9BQ0NPVU5UEAISGgoWTk9ERV9ST0xFX01FVl9TRUFSQ0hFUhADEhcKE05PREVfUk9MRV9NVUxUSV9IVUIQBBIVChFOT0RFX1JPTEVfU09MX0hVQhAFEhUKEU5PREVfUk9MRV9TUExfSFVCEAYSEwoPTk9ERV9ST0xFX1dIQUxFEAcSGAoUTk9ERV9ST0xFX01QQ19NRU1CRVIQCBIUChBOT0RFX1JPTEVfTk9STUFMEAliBnByb3RvMw");

/**
 * Per-node analytics classification. Wire format follows proto enum
 * canonical JSON: ROLE_WHALE -> "ROLE_WHALE" by default. We use Buf's
 * Connect protocol convention of stripping the prefix on the wire so
 * frontend/Python see the natural names ("whale", "tip-account", etc.)
 *
 * (Implementation note: protobuf enum JSON encoding emits the enum value
 * name as a string. Our generated TS will see `NodeRole.WHALE` etc.)
 *
 * @generated from enum multichain.wire.shared.v1.NodeRole
 */
export enum NodeRole {
  /**
   * @generated from enum value: NODE_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: NODE_ROLE_TOKEN_MINT = 1;
   */
  TOKEN_MINT = 1,

  /**
   * @generated from enum value: NODE_ROLE_TIP_ACCOUNT = 2;
   */
  TIP_ACCOUNT = 2,

  /**
   * @generated from enum value: NODE_ROLE_MEV_SEARCHER = 3;
   */
  MEV_SEARCHER = 3,

  /**
   * @generated from enum value: NODE_ROLE_MULTI_HUB = 4;
   */
  MULTI_HUB = 4,

  /**
   * @generated from enum value: NODE_ROLE_SOL_HUB = 5;
   */
  SOL_HUB = 5,

  /**
   * @generated from enum value: NODE_ROLE_SPL_HUB = 6;
   */
  SPL_HUB = 6,

  /**
   * @generated from enum value: NODE_ROLE_WHALE = 7;
   */
  WHALE = 7,

  /**
   * @generated from enum value: NODE_ROLE_MPC_MEMBER = 8;
   */
  MPC_MEMBER = 8,

  /**
   * @generated from enum value: NODE_ROLE_NORMAL = 9;
   */
  NORMAL = 9,
}

/**
 * Describes the enum multichain.wire.shared.v1.NodeRole.
 */
export const NodeRoleSchema: GenEnum<NodeRole> = /*@__PURE__*/
  enumDesc(file_multichain_wire_shared_v1_role, 0);

