// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file multichain/wire/shared/v1/scope.proto (package multichain.wire.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/shared/v1/scope.proto.
 */
export const file_multichain_wire_shared_v1_scope: GenFile = /*@__PURE__*/
  fileDesc("CiVtdWx0aWNoYWluL3dpcmUvc2hhcmVkL3YxL3Njb3BlLnByb3RvEhltdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxIoIBCglUaW1lU2NvcGUSNAoEbGl2ZRgBIAEoCzIkLm11bHRpY2hhaW4ud2lyZS5zaGFyZWQudjEuTGl2ZVNjb3BlSAASNgoFcmFuZ2UYAiABKAsyJS5tdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxLlJhbmdlU2NvcGVIAEIHCgVzY29wZSILCglMaXZlU2NvcGUiKgoKUmFuZ2VTY29wZRIOCgZmcm9tX3MYASABKA0SDAoEdG9fcxgCIAEoDSpwCglDb3N0Q2xhc3MSGgoWQ09TVF9DTEFTU19VTlNQRUNJRklFRBAAEhQKEENPU1RfQ0xBU1NfQ0hFQVAQARIXChNDT1NUX0NMQVNTX01PREVSQVRFEAISGAoUQ09TVF9DTEFTU19FWFBFTlNJVkUQAyp0CgpEYXRhU291cmNlEhsKF0RBVEFfU09VUkNFX1VOU1BFQ0lGSUVEEAASFAoQREFUQV9TT1VSQ0VfTElWRRABEhkKFURBVEFfU09VUkNFX1dBUkVIT1VTRRACEhgKFERBVEFfU09VUkNFX0VYVEVSTkFMEANiBnByb3RvMw");

/**
 * Mandatory temporal frame for primitives that have one (per D-6).
 *
 * The wire format follows proto canonical JSON encoding:
 *   Live  -> {"live": {}}
 *   Range -> {"range": {"fromS": "<u32>", "toS": "<u32>"}}
 *
 * (Note: this differs from the previous internally-tagged Rust wire shape
 * `{"range": {"from_s": ..., "to_s": ...}}` because proto's oneof always
 * produces an object wrapper. SSE goldens regenerate accordingly.)
 *
 * @generated from message multichain.wire.shared.v1.TimeScope
 */
export type TimeScope = Message<"multichain.wire.shared.v1.TimeScope"> & {
  /**
   * @generated from oneof multichain.wire.shared.v1.TimeScope.scope
   */
  scope: {
    /**
     * @generated from field: multichain.wire.shared.v1.LiveScope live = 1;
     */
    value: LiveScope;
    case: "live";
  } | {
    /**
     * @generated from field: multichain.wire.shared.v1.RangeScope range = 2;
     */
    value: RangeScope;
    case: "range";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message multichain.wire.shared.v1.TimeScope.
 * Use `create(TimeScopeSchema)` to create a new message.
 */
export const TimeScopeSchema: GenMessage<TimeScope> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_scope, 0);

/**
 * Current rolling live window. Empty marker; presence in the oneof is
 * the signal.
 *
 * @generated from message multichain.wire.shared.v1.LiveScope
 */
export type LiveScope = Message<"multichain.wire.shared.v1.LiveScope"> & {
};

/**
 * Describes the message multichain.wire.shared.v1.LiveScope.
 * Use `create(LiveScopeSchema)` to create a new message.
 */
export const LiveScopeSchema: GenMessage<LiveScope> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_scope, 1);

/**
 * Absolute block-time range. Routes to warehouse path (ship-5).
 *
 * @generated from message multichain.wire.shared.v1.RangeScope
 */
export type RangeScope = Message<"multichain.wire.shared.v1.RangeScope"> & {
  /**
   * @generated from field: uint32 from_s = 1;
   */
  fromS: number;

  /**
   * @generated from field: uint32 to_s = 2;
   */
  toS: number;
};

/**
 * Describes the message multichain.wire.shared.v1.RangeScope.
 * Use `create(RangeScopeSchema)` to create a new message.
 */
export const RangeScopeSchema: GenMessage<RangeScope> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_scope, 2);

/**
 * Primitive cost-class tag. Ship-4's budget gate reads this. Not currently
 * emitted on the wire but defined here so future primitives can use it
 * without adding a separate wire shape.
 *
 * @generated from enum multichain.wire.shared.v1.CostClass
 */
export enum CostClass {
  /**
   * @generated from enum value: COST_CLASS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: COST_CLASS_CHEAP = 1;
   */
  CHEAP = 1,

  /**
   * @generated from enum value: COST_CLASS_MODERATE = 2;
   */
  MODERATE = 2,

  /**
   * @generated from enum value: COST_CLASS_EXPENSIVE = 3;
   */
  EXPENSIVE = 3,
}

/**
 * Describes the enum multichain.wire.shared.v1.CostClass.
 */
export const CostClassSchema: GenEnum<CostClass> = /*@__PURE__*/
  enumDesc(file_multichain_wire_shared_v1_scope, 0);

/**
 * Primitive data source family per D-5.
 *
 * @generated from enum multichain.wire.shared.v1.DataSource
 */
export enum DataSource {
  /**
   * @generated from enum value: DATA_SOURCE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DATA_SOURCE_LIVE = 1;
   */
  LIVE = 1,

  /**
   * @generated from enum value: DATA_SOURCE_WAREHOUSE = 2;
   */
  WAREHOUSE = 2,

  /**
   * @generated from enum value: DATA_SOURCE_EXTERNAL = 3;
   */
  EXTERNAL = 3,
}

/**
 * Describes the enum multichain.wire.shared.v1.DataSource.
 */
export const DataSourceSchema: GenEnum<DataSource> = /*@__PURE__*/
  enumDesc(file_multichain_wire_shared_v1_scope, 1);

