// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file multichain/wire/shared/v1/snapshot.proto (package multichain.wire.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/shared/v1/snapshot.proto.
 */
export const file_multichain_wire_shared_v1_snapshot: GenFile = /*@__PURE__*/
  fileDesc("CihtdWx0aWNoYWluL3dpcmUvc2hhcmVkL3YxL3NuYXBzaG90LnByb3RvEhltdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxIlgKFVNuYXBzaG90QmVnaW5SZXNwb25zZRITCgtzbmFwc2hvdF9pZBgBIAEoCRIVCg1leHBpcmVzX2F0X21zGAIgASgEEhMKC3dpbmRvd19zZWNzGAMgASgNIikKElNuYXBzaG90RW5kUmVxdWVzdBITCgtzbmFwc2hvdF9pZBgBIAEoCWIGcHJvdG8z");

/**
 * Response from `POST /turn/begin`. The Python agent stashes the
 * snapshot_id and passes it on every subsequent primitive call in
 * the same turn so reads are consistent across primitives even if
 * new blocks ingest mid-turn.
 *
 * `expires_at_ms` is a wallclock floor; the actual GC sweep on the
 * Rust side may keep the snapshot slightly longer. After this time
 * the Python client must re-`/turn/begin`.
 *
 * @generated from message multichain.wire.shared.v1.SnapshotBeginResponse
 */
export type SnapshotBeginResponse = Message<"multichain.wire.shared.v1.SnapshotBeginResponse"> & {
  /**
   * @generated from field: string snapshot_id = 1;
   */
  snapshotId: string;

  /**
   * @generated from field: uint64 expires_at_ms = 2;
   */
  expiresAtMs: bigint;

  /**
   * The window the snapshot was materialized at (matches the agent's
   * live window). Phase A only supports 60s; future ships may add
   * a `window_secs` field on the begin request to negotiate.
   *
   * @generated from field: uint32 window_secs = 3;
   */
  windowSecs: number;
};

/**
 * Describes the message multichain.wire.shared.v1.SnapshotBeginResponse.
 * Use `create(SnapshotBeginResponseSchema)` to create a new message.
 */
export const SnapshotBeginResponseSchema: GenMessage<SnapshotBeginResponse> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_snapshot, 0);

/**
 * Body of `POST /turn/end`. Releases the snapshot eagerly. Optional;
 * the GC sweep would clean it up within 5 minutes anyway, but eager
 * release keeps the cache small for healthy turns.
 *
 * @generated from message multichain.wire.shared.v1.SnapshotEndRequest
 */
export type SnapshotEndRequest = Message<"multichain.wire.shared.v1.SnapshotEndRequest"> & {
  /**
   * @generated from field: string snapshot_id = 1;
   */
  snapshotId: string;
};

/**
 * Describes the message multichain.wire.shared.v1.SnapshotEndRequest.
 * Use `create(SnapshotEndRequestSchema)` to create a new message.
 */
export const SnapshotEndRequestSchema: GenMessage<SnapshotEndRequest> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_snapshot, 1);

