// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file multichain/wire/shared/v1/subgraph.proto (package multichain.wire.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/shared/v1/subgraph.proto.
 */
export const file_multichain_wire_shared_v1_subgraph: GenFile = /*@__PURE__*/
  fileDesc("CihtdWx0aWNoYWluL3dpcmUvc2hhcmVkL3YxL3N1YmdyYXBoLnByb3RvEhltdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxIssBCg1TdWJncmFwaFNsaWNlEjUKBW5vZGVzGAEgAygLMiYubXVsdGljaGFpbi53aXJlLnNoYXJlZC52MS5Ob2RlU3VtbWFyeRI1CgVlZGdlcxgCIAMoCzImLm11bHRpY2hhaW4ud2lyZS5zaGFyZWQudjEuRWRnZVN1bW1hcnkSPQoKdGltZV9yYW5nZRgDIAEoCzIkLm11bHRpY2hhaW4ud2lyZS5zaGFyZWQudjEuVGltZVJhbmdlSACIAQFCDQoLX3RpbWVfcmFuZ2UiNwoLTm9kZVN1bW1hcnkSDAoEYWRkchgBIAEoCRIRCgRyb2xlGAIgASgJSACIAQFCBwoFX3JvbGUiNwoLRWRnZVN1bW1hcnkSCwoDc3JjGAEgASgJEgsKA2RzdBgCIAEoCRIOCgZ2b2x1bWUYAyABKAEiKQoJVGltZVJhbmdlEg4KBmZyb21fcxgBIAEoDRIMCgR0b19zGAIgASgNYgZwcm90bzM");

/**
 * Self-contained subgraph rendered on its own canvas in a modal.
 * Used by ship-5 for historical results that don't share layout
 * state with the live graph.
 *
 * @generated from message multichain.wire.shared.v1.SubgraphSlice
 */
export type SubgraphSlice = Message<"multichain.wire.shared.v1.SubgraphSlice"> & {
  /**
   * @generated from field: repeated multichain.wire.shared.v1.NodeSummary nodes = 1;
   */
  nodes: NodeSummary[];

  /**
   * @generated from field: repeated multichain.wire.shared.v1.EdgeSummary edges = 2;
   */
  edges: EdgeSummary[];

  /**
   * @generated from field: optional multichain.wire.shared.v1.TimeRange time_range = 3;
   */
  timeRange?: TimeRange | undefined;
};

/**
 * Describes the message multichain.wire.shared.v1.SubgraphSlice.
 * Use `create(SubgraphSliceSchema)` to create a new message.
 */
export const SubgraphSliceSchema: GenMessage<SubgraphSlice> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_subgraph, 0);

/**
 * @generated from message multichain.wire.shared.v1.NodeSummary
 */
export type NodeSummary = Message<"multichain.wire.shared.v1.NodeSummary"> & {
  /**
   * @generated from field: string addr = 1;
   */
  addr: string;

  /**
   * None when the role is unclassified.
   *
   * @generated from field: optional string role = 2;
   */
  role?: string | undefined;
};

/**
 * Describes the message multichain.wire.shared.v1.NodeSummary.
 * Use `create(NodeSummarySchema)` to create a new message.
 */
export const NodeSummarySchema: GenMessage<NodeSummary> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_subgraph, 1);

/**
 * @generated from message multichain.wire.shared.v1.EdgeSummary
 */
export type EdgeSummary = Message<"multichain.wire.shared.v1.EdgeSummary"> & {
  /**
   * @generated from field: string src = 1;
   */
  src: string;

  /**
   * @generated from field: string dst = 2;
   */
  dst: string;

  /**
   * Lamports.
   *
   * @generated from field: double volume = 3;
   */
  volume: number;
};

/**
 * Describes the message multichain.wire.shared.v1.EdgeSummary.
 * Use `create(EdgeSummarySchema)` to create a new message.
 */
export const EdgeSummarySchema: GenMessage<EdgeSummary> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_subgraph, 2);

/**
 * Wire-friendly time range used inside a subgraph slice. Distinct from
 * the `TimeRangeRef` ProvenanceRef variant.
 *
 * @generated from message multichain.wire.shared.v1.TimeRange
 */
export type TimeRange = Message<"multichain.wire.shared.v1.TimeRange"> & {
  /**
   * @generated from field: uint32 from_s = 1;
   */
  fromS: number;

  /**
   * @generated from field: uint32 to_s = 2;
   */
  toS: number;
};

/**
 * Describes the message multichain.wire.shared.v1.TimeRange.
 * Use `create(TimeRangeSchema)` to create a new message.
 */
export const TimeRangeSchema: GenMessage<TimeRange> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_subgraph, 3);

