// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file multichain/wire/shared/v1/wallet_profile.proto (package multichain.wire.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { NodeRole } from "./role_pb.js";
import { file_multichain_wire_shared_v1_role } from "./role_pb.js";
import type { TimeScope } from "./scope_pb.js";
import { file_multichain_wire_shared_v1_scope } from "./scope_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multichain/wire/shared/v1/wallet_profile.proto.
 */
export const file_multichain_wire_shared_v1_wallet_profile: GenFile = /*@__PURE__*/
  fileDesc("Ci5tdWx0aWNoYWluL3dpcmUvc2hhcmVkL3YxL3dhbGxldF9wcm9maWxlLnByb3RvEhltdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxIlwKEldhbGxldFByb2ZpbGVJbnB1dBIMCgRhZGRyGAEgASgJEjgKCnRpbWVfc2NvcGUYAiABKAsyJC5tdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxLlRpbWVTY29wZSKbAgoTV2FsbGV0UHJvZmlsZU91dHB1dBIMCgRhZGRyGAEgASgJEjEKBHJvbGUYAiABKA4yIy5tdWx0aWNoYWluLndpcmUuc2hhcmVkLnYxLk5vZGVSb2xlEhkKDGNvbW11bml0eV9pZBgDIAEoDUgAiAEBEjMKBXN0YXRzGAQgASgLMiQubXVsdGljaGFpbi53aXJlLnNoYXJlZC52MS5Ob2RlU3RhdHMSRgoSdG9wX2NvdW50ZXJwYXJ0aWVzGAUgAygLMioubXVsdGljaGFpbi53aXJlLnNoYXJlZC52MS5Ub3BDb3VudGVycGFydHkSGgoSYWdlX2luX3dpbmRvd19zZWNzGAYgASgNQg8KDV9jb21tdW5pdHlfaWQiugEKCU5vZGVTdGF0cxIOCgZkZWdyZWUYASABKA0SHQoVdG90YWxfdm9sdW1lX2xhbXBvcnRzGAIgASgBEhoKEmluX3ZvbHVtZV9sYW1wb3J0cxgDIAEoARIbChNvdXRfdm9sdW1lX2xhbXBvcnRzGAQgASgBEh0KFWJpZGlyX3ZvbHVtZV9sYW1wb3J0cxgFIAEoARISCgpzb2xfZGVncmVlGAYgASgNEhIKCnNwbF9kZWdyZWUYByABKA0iLwoPVG9wQ291bnRlcnBhcnR5EgwKBGFkZHIYASABKAkSDgoGdm9sdW1lGAIgASgBYgZwcm90bzM", [file_multichain_wire_shared_v1_role, file_multichain_wire_shared_v1_scope]);

/**
 * Input to the `wallet_profile` primitive. The agent passes a wallet
 * address and a TimeScope; live arm is the current live window,
 * range arm routes to the warehouse path (ship-5).
 *
 * @generated from message multichain.wire.shared.v1.WalletProfileInput
 */
export type WalletProfileInput = Message<"multichain.wire.shared.v1.WalletProfileInput"> & {
  /**
   * Solana base58 pubkey.
   *
   * @generated from field: string addr = 1;
   */
  addr: string;

  /**
   * @generated from field: multichain.wire.shared.v1.TimeScope time_scope = 2;
   */
  timeScope?: TimeScope | undefined;
};

/**
 * Describes the message multichain.wire.shared.v1.WalletProfileInput.
 * Use `create(WalletProfileInputSchema)` to create a new message.
 */
export const WalletProfileInputSchema: GenMessage<WalletProfileInput> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_wallet_profile, 0);

/**
 * Output of the `wallet_profile` primitive. The agent reads this to
 * build the profile claim.
 *
 * @generated from message multichain.wire.shared.v1.WalletProfileOutput
 */
export type WalletProfileOutput = Message<"multichain.wire.shared.v1.WalletProfileOutput"> & {
  /**
   * @generated from field: string addr = 1;
   */
  addr: string;

  /**
   * Defaults to NORMAL when unclassified.
   *
   * @generated from field: multichain.wire.shared.v1.NodeRole role = 2;
   */
  role: NodeRole;

  /**
   * Stable community label (u32) reported by analytics. Zero is a
   * valid community id; absence is signaled via the optional flag.
   *
   * @generated from field: optional uint32 community_id = 3;
   */
  communityId?: number | undefined;

  /**
   * @generated from field: multichain.wire.shared.v1.NodeStats stats = 4;
   */
  stats?: NodeStats | undefined;

  /**
   * Capped at 5 by primitive impl.
   *
   * @generated from field: repeated multichain.wire.shared.v1.TopCounterparty top_counterparties = 5;
   */
  topCounterparties: TopCounterparty[];

  /**
   * Seconds since the wallet first appeared in the current live window.
   *
   * @generated from field: uint32 age_in_window_secs = 6;
   */
  ageInWindowSecs: number;
};

/**
 * Describes the message multichain.wire.shared.v1.WalletProfileOutput.
 * Use `create(WalletProfileOutputSchema)` to create a new message.
 */
export const WalletProfileOutputSchema: GenMessage<WalletProfileOutput> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_wallet_profile, 1);

/**
 * Wire mirror of analytics::snapshot::NodeStats. Field names use the
 * descriptive `*_volume_lamports` form so that the structural value-
 * compare gate (policy_structural::verify_chip_values) classifies them
 * as `UnitClass::Sol` via substring match on "volume" + "lamport".
 *
 * @generated from message multichain.wire.shared.v1.NodeStats
 */
export type NodeStats = Message<"multichain.wire.shared.v1.NodeStats"> & {
  /**
   * @generated from field: uint32 degree = 1;
   */
  degree: number;

  /**
   * @generated from field: double total_volume_lamports = 2;
   */
  totalVolumeLamports: number;

  /**
   * @generated from field: double in_volume_lamports = 3;
   */
  inVolumeLamports: number;

  /**
   * @generated from field: double out_volume_lamports = 4;
   */
  outVolumeLamports: number;

  /**
   * @generated from field: double bidir_volume_lamports = 5;
   */
  bidirVolumeLamports: number;

  /**
   * @generated from field: uint32 sol_degree = 6;
   */
  solDegree: number;

  /**
   * @generated from field: uint32 spl_degree = 7;
   */
  splDegree: number;
};

/**
 * Describes the message multichain.wire.shared.v1.NodeStats.
 * Use `create(NodeStatsSchema)` to create a new message.
 */
export const NodeStatsSchema: GenMessage<NodeStats> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_wallet_profile, 2);

/**
 * @generated from message multichain.wire.shared.v1.TopCounterparty
 */
export type TopCounterparty = Message<"multichain.wire.shared.v1.TopCounterparty"> & {
  /**
   * @generated from field: string addr = 1;
   */
  addr: string;

  /**
   * Lamports.
   *
   * @generated from field: double volume = 2;
   */
  volume: number;
};

/**
 * Describes the message multichain.wire.shared.v1.TopCounterparty.
 * Use `create(TopCounterpartySchema)` to create a new message.
 */
export const TopCounterpartySchema: GenMessage<TopCounterparty> = /*@__PURE__*/
  messageDesc(file_multichain_wire_shared_v1_wallet_profile, 3);

