"""Build `wire/shared/__init__.py` from the per-type modules
`datamodel-codegen` produced. The input schema files are PascalCase
(`WalletProfileInput.json` etc); datamodel-codegen preserves file
names so each type's canonical module is `wire/shared/<TypeName>.py`.

This script wires up the package init so callers can write:

    from agent_service.wire.shared import WalletProfileInput

instead of poking at per-type submodules.

Run via the `regen-shared-types` recipe; not invoked directly.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WIRE_DIR = ROOT / "src" / "agent_service" / "wire" / "shared"


def main() -> None:
    if not WIRE_DIR.exists():
        raise SystemExit(
            f"{WIRE_DIR} missing. Run `cargo run --bin dump_schemas` "
            "and `datamodel-codegen` first."
        )

    schema_dir = ROOT / "src" / "agent_service" / "wire" / "schemas-shared"
    type_names: list[str] = sorted(p.stem for p in schema_dir.glob("*.json"))

    lines: list[str] = [
        '"""Auto-generated shim. Re-exports every shared wire type from',
        "its per-type submodule. DO NOT HAND-EDIT; rerun",
        "`just regen-wire-types` to regenerate.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]

    # Each type lives in its own module with a matching name. The
    # module is the canonical home; per-type modules generated by
    # datamodel-codegen may also redefine helper types (e.g.
    # `NodeStatsWire` appears in both `NodeStatsWire.py` and inline
    # inside `WalletProfileOutput.py`). The init re-exports from the
    # canonical module so identity is unambiguous.
    for name in type_names:
        lines.append(f"from .{name} import {name}")

    lines.append("")
    lines.append("__all__ = [")
    for name in type_names:
        lines.append(f'    "{name}",')
    lines.append("]")
    lines.append("")

    init_path = WIRE_DIR / "__init__.py"
    init_path.write_text("\n".join(lines))
    print(f"wrote {init_path} ({len(type_names)} re-exports)")


if __name__ == "__main__":
    main()
