# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multichain/wire/agent/v1/constitution.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'multichain/wire/agent/v1/constitution.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+multichain/wire/agent/v1/constitution.proto\x12\x18multichain.wire.agent.v1\"\xa4\x01\n\x13\x43onstitutionVerdict\x12\x18\n\x07verdict\x18\x01 \x01(\tR\x07verdict\x12\x16\n\x06reason\x18\x02 \x01(\tR\x06reason\x12L\n\nextraction\x18\x03 \x01(\x0b\x32\'.multichain.wire.agent.v1.LlmExtractionH\x00R\nextraction\x88\x01\x01\x42\r\n\x0b_extraction\"\xbd\x01\n\rLlmExtraction\x12Y\n\x11narrative_numbers\x18\x01 \x03(\x0b\x32,.multichain.wire.agent.v1.LlmExtractedNumberR\x10narrativeNumbers\x12Q\n\rclaim_numbers\x18\x02 \x03(\x0b\x32,.multichain.wire.agent.v1.LlmExtractedNumberR\x0c\x63laimNumbers\"a\n\x12LlmExtractedNumber\x12\x14\n\x05value\x18\x01 \x01(\x01R\x05value\x12\x1d\n\nunit_class\x18\x02 \x01(\tR\tunitClass\x12\x16\n\x06phrase\x18\x03 \x01(\tR\x06phraseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multichain.wire.agent.v1.constitution_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSTITUTIONVERDICT']._serialized_start=74
  _globals['_CONSTITUTIONVERDICT']._serialized_end=238
  _globals['_LLMEXTRACTION']._serialized_start=241
  _globals['_LLMEXTRACTION']._serialized_end=430
  _globals['_LLMEXTRACTEDNUMBER']._serialized_start=432
  _globals['_LLMEXTRACTEDNUMBER']._serialized_end=529
# @@protoc_insertion_point(module_scope)
