# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multichain/wire/agent/v1/diff.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'multichain/wire/agent/v1/diff.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#multichain/wire/agent/v1/diff.proto\x12\x18multichain.wire.agent.v1\"\\\n\nNoMovement\x12\x1d\n\nprior_turn\x18\x01 \x01(\rR\tpriorTurn\x12/\n\x13primitives_replayed\x18\x02 \x03(\tR\x12primitivesReplayed\"z\n\x0c\x43hangedSince\x12\x1d\n\nprior_turn\x18\x01 \x01(\rR\tpriorTurn\x12\x35\n\x05\x64\x65lta\x18\x02 \x01(\x0b\x32\x1f.multichain.wire.agent.v1.DeltaR\x05\x64\x65lta\x12\x14\n\x05prose\x18\x03 \x01(\tR\x05prose\"{\n\x05\x44\x65lta\x12>\n\x07\x63hanged\x18\x01 \x03(\x0b\x32$.multichain.wire.agent.v1.FieldDeltaR\x07\x63hanged\x12\x32\n\x15unchanged_field_count\x18\x02 \x01(\rR\x13unchangedFieldCount\"\x88\x01\n\nFieldDelta\x12\x1d\n\nfield_path\x18\x01 \x01(\tR\tfieldPath\x12\x1c\n\tprimitive\x18\x02 \x01(\tR\tprimitive\x12=\n\x06\x63hange\x18\x03 \x01(\x0b\x32%.multichain.wire.agent.v1.FieldChangeR\x06\x63hange\"\x9c\x02\n\x0b\x46ieldChange\x12U\n\x0cnumber_moved\x18\x01 \x01(\x0b\x32\x30.multichain.wire.agent.v1.FieldChangeNumberMovedH\x00R\x0bnumberMoved\x12R\n\x0bset_changed\x18\x02 \x01(\x0b\x32/.multichain.wire.agent.v1.FieldChangeSetChangedH\x00R\nsetChanged\x12X\n\rcount_changed\x18\x03 \x01(\x0b\x32\x31.multichain.wire.agent.v1.FieldChangeCountChangedH\x00R\x0c\x63ountChangedB\x08\n\x06\x63hange\"Z\n\x16\x46ieldChangeNumberMoved\x12\x14\n\x05prior\x18\x01 \x01(\x01R\x05prior\x12\x18\n\x07\x63urrent\x18\x02 \x01(\x01R\x07\x63urrent\x12\x10\n\x03pct\x18\x03 \x01(\x01R\x03pct\"G\n\x15\x46ieldChangeSetChanged\x12\x14\n\x05\x61\x64\x64\x65\x64\x18\x01 \x03(\tR\x05\x61\x64\x64\x65\x64\x12\x18\n\x07removed\x18\x02 \x03(\tR\x07removed\"I\n\x17\x46ieldChangeCountChanged\x12\x14\n\x05prior\x18\x01 \x01(\x01R\x05prior\x12\x18\n\x07\x63urrent\x18\x02 \x01(\x01R\x07\x63urrentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multichain.wire.agent.v1.diff_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOMOVEMENT']._serialized_start=65
  _globals['_NOMOVEMENT']._serialized_end=157
  _globals['_CHANGEDSINCE']._serialized_start=159
  _globals['_CHANGEDSINCE']._serialized_end=281
  _globals['_DELTA']._serialized_start=283
  _globals['_DELTA']._serialized_end=406
  _globals['_FIELDDELTA']._serialized_start=409
  _globals['_FIELDDELTA']._serialized_end=545
  _globals['_FIELDCHANGE']._serialized_start=548
  _globals['_FIELDCHANGE']._serialized_end=832
  _globals['_FIELDCHANGENUMBERMOVED']._serialized_start=834
  _globals['_FIELDCHANGENUMBERMOVED']._serialized_end=924
  _globals['_FIELDCHANGESETCHANGED']._serialized_start=926
  _globals['_FIELDCHANGESETCHANGED']._serialized_end=997
  _globals['_FIELDCHANGECOUNTCHANGED']._serialized_start=999
  _globals['_FIELDCHANGECOUNTCHANGED']._serialized_end=1072
# @@protoc_insertion_point(module_scope)
