# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multichain/wire/agent/v1/entity.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'multichain/wire/agent/v1/entity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%multichain/wire/agent/v1/entity.proto\x12\x18multichain.wire.agent.v1\"\xe7\x01\n\tEntityRef\x12\x43\n\x06wallet\x18\x01 \x01(\x0b\x32).multichain.wire.agent.v1.EntityRefWalletH\x00R\x06wallet\x12=\n\x04\x65\x64ge\x18\x02 \x01(\x0b\x32\'.multichain.wire.agent.v1.EntityRefEdgeH\x00R\x04\x65\x64ge\x12L\n\tcommunity\x18\x03 \x01(\x0b\x32,.multichain.wire.agent.v1.EntityRefCommunityH\x00R\tcommunityB\x08\n\x06\x65ntity\"!\n\x0f\x45ntityRefWallet\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n\rEntityRefEdge\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"$\n\x12\x45ntityRefCommunity\x12\x0e\n\x02id\x18\x01 \x01(\rR\x02id\"\xc4\x01\n\x0bViewContext\x12(\n\x10live_window_secs\x18\x01 \x01(\rR\x0eliveWindowSecs\x12>\n\x05\x66ocus\x18\x02 \x01(\x0b\x32#.multichain.wire.agent.v1.EntityRefH\x00R\x05\x66ocus\x88\x01\x01\x12\x41\n\tselection\x18\x03 \x03(\x0b\x32#.multichain.wire.agent.v1.EntityRefR\tselectionB\x08\n\x06_focusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multichain.wire.agent.v1.entity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTITYREF']._serialized_start=68
  _globals['_ENTITYREF']._serialized_end=299
  _globals['_ENTITYREFWALLET']._serialized_start=301
  _globals['_ENTITYREFWALLET']._serialized_end=334
  _globals['_ENTITYREFEDGE']._serialized_start=336
  _globals['_ENTITYREFEDGE']._serialized_end=367
  _globals['_ENTITYREFCOMMUNITY']._serialized_start=369
  _globals['_ENTITYREFCOMMUNITY']._serialized_end=405
  _globals['_VIEWCONTEXT']._serialized_start=408
  _globals['_VIEWCONTEXT']._serialized_end=604
# @@protoc_insertion_point(module_scope)
