# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multichain/wire/agent/v1/history.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'multichain/wire/agent/v1/history.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from multichain.wire.agent.v1 import claim_pb2 as multichain_dot_wire_dot_agent_dot_v1_dot_claim__pb2
from multichain.wire.agent.v1 import session_pb2 as multichain_dot_wire_dot_agent_dot_v1_dot_session__pb2
from multichain.wire.shared.v1 import provenance_pb2 as multichain_dot_wire_dot_shared_dot_v1_dot_provenance__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&multichain/wire/agent/v1/history.proto\x12\x18multichain.wire.agent.v1\x1a$multichain/wire/agent/v1/claim.proto\x1a&multichain/wire/agent/v1/session.proto\x1a*multichain/wire/shared/v1/provenance.proto\"\x91\x02\n\rThreadSummary\x12\x1b\n\tthread_id\x18\x01 \x01(\tR\x08threadId\x12@\n\x07runtime\x18\x02 \x01(\x0e\x32&.multichain.wire.agent.v1.AgentRuntimeR\x07runtime\x12\"\n\rstarted_at_ms\x18\x03 \x01(\x04R\x0bstartedAtMs\x12\x1d\n\nturn_count\x18\x04 \x01(\rR\tturnCount\x12\x14\n\x05title\x18\x05 \x01(\tR\x05title\x12,\n\x12last_user_question\x18\x06 \x01(\tR\x10lastUserQuestion\x12\x1a\n\x08\x61rchived\x18\x07 \x01(\x08R\x08\x61rchived\"O\n\nThreadList\x12\x41\n\x07threads\x18\x01 \x03(\x0b\x32\'.multichain.wire.agent.v1.ThreadSummaryR\x07threads\"\xc4\x02\n\x0eTranscriptTurn\x12\x12\n\x04turn\x18\x01 \x01(\rR\x04turn\x12#\n\ruser_question\x18\x02 \x01(\tR\x0cuserQuestion\x12\x37\n\x06\x63laims\x18\x03 \x03(\x0b\x32\x1f.multichain.wire.agent.v1.ClaimR\x06\x63laims\x12%\n\x0enarrative_text\x18\x04 \x01(\tR\rnarrativeText\x12[\n\x14narrative_provenance\x18\x05 \x03(\x0b\x32(.multichain.wire.shared.v1.ProvenanceRefR\x13narrativeProvenance\x12<\n\x1anarrative_retracted_reason\x18\x06 \x01(\tR\x18narrativeRetractedReason\"\x93\x01\n\x10ThreadTranscript\x12?\n\x06thread\x18\x01 \x01(\x0b\x32\'.multichain.wire.agent.v1.ThreadSummaryR\x06thread\x12>\n\x05turns\x18\x02 \x03(\x0b\x32(.multichain.wire.agent.v1.TranscriptTurnR\x05turnsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multichain.wire.agent.v1.history_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THREADSUMMARY']._serialized_start=191
  _globals['_THREADSUMMARY']._serialized_end=464
  _globals['_THREADLIST']._serialized_start=466
  _globals['_THREADLIST']._serialized_end=545
  _globals['_TRANSCRIPTTURN']._serialized_start=548
  _globals['_TRANSCRIPTTURN']._serialized_end=872
  _globals['_THREADTRANSCRIPT']._serialized_start=875
  _globals['_THREADTRANSCRIPT']._serialized_end=1022
# @@protoc_insertion_point(module_scope)
