# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multichain/wire/agent/v1/llm.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'multichain/wire/agent/v1/llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"multichain/wire/agent/v1/llm.proto\x12\x18multichain.wire.agent.v1\"\xcd\x01\n\x0bLlmOverride\x12@\n\x07primary\x18\x01 \x01(\x0b\x32&.multichain.wire.agent.v1.RoleOverrideR\x07primary\x12>\n\x06policy\x18\x02 \x01(\x0b\x32&.multichain.wire.agent.v1.RoleOverrideR\x06policy\x12<\n\x05judge\x18\x03 \x01(\x0b\x32&.multichain.wire.agent.v1.RoleOverrideR\x05judge\"E\n\x0cRoleOverride\x12\x1a\n\x08provider\x18\x01 \x01(\tR\x08provider\x12\x19\n\x08model_id\x18\x02 \x01(\tR\x07modelIdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multichain.wire.agent.v1.llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LLMOVERRIDE']._serialized_start=65
  _globals['_LLMOVERRIDE']._serialized_end=270
  _globals['_ROLEOVERRIDE']._serialized_start=272
  _globals['_ROLEOVERRIDE']._serialized_end=341
# @@protoc_insertion_point(module_scope)
