# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multichain/wire/agent/v1/session.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'multichain/wire/agent/v1/session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from multichain.wire.agent.v1 import entity_pb2 as multichain_dot_wire_dot_agent_dot_v1_dot_entity__pb2
from multichain.wire.agent.v1 import switches_pb2 as multichain_dot_wire_dot_agent_dot_v1_dot_switches__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&multichain/wire/agent/v1/session.proto\x12\x18multichain.wire.agent.v1\x1a%multichain/wire/agent/v1/entity.proto\x1a\'multichain/wire/agent/v1/switches.proto\"\x88\x02\n\x0c\x41gentRequest\x12#\n\ruser_question\x18\x01 \x01(\tR\x0cuserQuestion\x12?\n\x07\x63ontext\x18\x02 \x01(\x0b\x32%.multichain.wire.agent.v1.ViewContextR\x07\x63ontext\x12 \n\tthread_id\x18\x03 \x01(\tH\x00R\x08threadId\x88\x01\x01\x12\x43\n\x08switches\x18\x04 \x01(\x0b\x32\'.multichain.wire.agent.v1.AgentSwitchesR\x08switches\x12\x1d\n\nshow_trace\x18\x05 \x01(\x08R\tshowTraceB\x0c\n\n_thread_id\"e\n\x13\x41gentSessionStarted\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n\tthread_id\x18\x02 \x01(\tR\x08threadId\x12\x12\n\x04turn\x18\x03 \x01(\rR\x04turn\"d\n\tAgentDone\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n\nelapsed_ms\x18\x02 \x01(\rR\telapsedMs\x12\x19\n\x08trace_id\x18\x03 \x01(\tR\x07traceIdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multichain.wire.agent.v1.session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTREQUEST']._serialized_start=149
  _globals['_AGENTREQUEST']._serialized_end=413
  _globals['_AGENTSESSIONSTARTED']._serialized_start=415
  _globals['_AGENTSESSIONSTARTED']._serialized_end=516
  _globals['_AGENTDONE']._serialized_start=518
  _globals['_AGENTDONE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
