# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multichain/wire/agent/v1/sse.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'multichain/wire/agent/v1/sse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from multichain.wire.agent.v1 import policy_pb2 as multichain_dot_wire_dot_agent_dot_v1_dot_policy__pb2
from multichain.wire.agent.v1 import switches_pb2 as multichain_dot_wire_dot_agent_dot_v1_dot_switches__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"multichain/wire/agent/v1/sse.proto\x12\x18multichain.wire.agent.v1\x1a%multichain/wire/agent/v1/policy.proto\x1a\'multichain/wire/agent/v1/switches.proto\"8\n\x08Progress\x12\x14\n\x05phase\x18\x01 \x01(\tR\x05phase\x12\x16\n\x06\x64\x65tail\x18\x02 \x01(\tR\x06\x64\x65tail\"]\n\x05\x45rror\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\x12(\n\rdebug_message\x18\x02 \x01(\tH\x00R\x0c\x64\x65\x62ugMessage\x88\x01\x01\x42\x10\n\x0e_debug_message\"\xf1\x01\n\x08GatePath\x12\x18\n\x07\x63hannel\x18\x01 \x01(\tR\x07\x63hannel\x12\x43\n\x08switches\x18\x02 \x01(\x0b\x32\'.multichain.wire.agent.v1.AgentSwitchesR\x08switches\x12\x38\n\x05steps\x18\x03 \x03(\x0b\x32\".multichain.wire.agent.v1.PathStepR\x05steps\x12L\n\rfinal_verdict\x18\x04 \x01(\x0b\x32\'.multichain.wire.agent.v1.PolicyVerdictR\x0c\x66inalVerdictb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multichain.wire.agent.v1.sse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROGRESS']._serialized_start=144
  _globals['_PROGRESS']._serialized_end=200
  _globals['_ERROR']._serialized_start=202
  _globals['_ERROR']._serialized_end=295
  _globals['_GATEPATH']._serialized_start=298
  _globals['_GATEPATH']._serialized_end=539
# @@protoc_insertion_point(module_scope)
