# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multichain/wire/agent/v1/switches.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'multichain/wire/agent/v1/switches.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'multichain/wire/agent/v1/switches.proto\x12\x18multichain.wire.agent.v1\"\xd9\x01\n\rAgentSwitches\x12 \n\x0cstay_in_role\x18\x01 \x01(\x08R\nstayInRole\x12%\n\x0e\x64ont_fabricate\x18\x02 \x01(\x08R\rdontFabricate\x12M\n\x0b\x63ross_check\x18\x03 \x01(\x0b\x32,.multichain.wire.agent.v1.CrossCheckSwitchesR\ncrossCheck\x12\x30\n\x14\x64ont_repeat_yourself\x18\x04 \x01(\x08R\x12\x64ontRepeatYourself\"x\n\x12\x43rossCheckSwitches\x12\x34\n\x16paraphrase_aware_match\x18\x01 \x01(\x08R\x14paraphraseAwareMatch\x12,\n\x12ground_truth_match\x18\x02 \x01(\x08R\x10groundTruthMatchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multichain.wire.agent.v1.switches_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTSWITCHES']._serialized_start=70
  _globals['_AGENTSWITCHES']._serialized_end=287
  _globals['_CROSSCHECKSWITCHES']._serialized_start=289
  _globals['_CROSSCHECKSWITCHES']._serialized_end=409
# @@protoc_insertion_point(module_scope)
