"""HTTP client wrapping the Rust data plane on :8002.

Phase A: snapshot lease. Python opens a snapshot via `POST /turn/begin`,
passes the returned `snapshot_id` on every primitive call this turn so
reads are consistent across primitives even if new blocks ingest mid-
turn, then releases via `POST /turn/end`.

All wire types are imported from `agent_service.wire.shared`, which is
auto-generated by `just regen-wire-types` from
`backend/src/wire/shared.rs`. Do NOT hand-write parallel pydantic
shapes here; if you need a new type, add it to the Rust source and
re-run the codegen.
"""

from __future__ import annotations

from typing import Any

import httpx
import structlog
from pydantic import BaseModel, ConfigDict

from .wire.shared import (
    CommunitySummaryInput,
    CommunitySummaryOutput,
    CommunitySummaryRequest,
    SnapshotBeginResponse,
    SnapshotEndRequest,
    WalletProfileInput,
    WalletProfileOutput,
    WalletProfileRequest,
)

log = structlog.get_logger(__name__)


class PrimitiveResponse(BaseModel):
    """Envelope every `/primitive/*` route returns. Mirrors
    `backend/src/api/primitives.rs::PrimitiveResponse` (the Rust serde
    shape; not the schemars one in `wire::shared` since the Rust route
    keeps the original generic envelope for performance)."""

    model_config = ConfigDict(extra="forbid")

    value: dict[str, Any]
    provenance: list[dict[str, Any]]
    subgraph_slice: dict[str, Any] | None = None


class PrimitiveError(Exception):
    """Mirror of Rust `PrimitiveError`. `kind` matches the JSON key
    returned by `error_response()` so the agent can branch.

    Special case: `snapshot_gone` (HTTP 410) means the snapshot the
    Python side held expired (GC swept it, or Rust restarted). The
    caller should `/turn/begin` a fresh snapshot and retry.
    """

    def __init__(self, kind: str, message: str, status_code: int):
        super().__init__(message)
        self.kind = kind
        self.message = message
        self.status_code = status_code


class PrimitiveClient:
    """Async client over the Rust data plane. Caller owns the lifecycle:
    build once at app startup, close on shutdown.

    Snapshot lease usage:
        snapshot_id = await client.begin_turn()
        try:
            out = await client.wallet_profile(input, snapshot_id)
        finally:
            await client.end_turn(snapshot_id)
    """

    def __init__(self, base_url: str, timeout_s: float = 30.0):
        self._client = httpx.AsyncClient(
            base_url=base_url,
            timeout=httpx.Timeout(timeout_s),
        )

    async def close(self) -> None:
        await self._client.aclose()

    # ---------------------------------------------------------------
    # Snapshot lease
    # ---------------------------------------------------------------

    async def begin_turn(self) -> SnapshotBeginResponse:
        resp = await self._client.post("/turn/begin")
        if resp.status_code >= 400:
            self._raise_from_error(resp)
        return SnapshotBeginResponse.model_validate(resp.json())

    async def end_turn(self, snapshot_id: str) -> None:
        """Idempotent. Failures are logged-and-swallowed because the GC
        sweep cleans up unreleased snapshots within 5 minutes; making
        this fatal would propagate transient network blips into the
        agent's user-facing error path."""
        try:
            body = SnapshotEndRequest(snapshot_id=snapshot_id).model_dump()
            resp = await self._client.post("/turn/end", json=body)
            if resp.status_code >= 400:
                log.warning(
                    "turn_end_non_2xx", status=resp.status_code, snapshot_id=snapshot_id
                )
        except Exception as e:  # noqa: BLE001
            log.warning("turn_end_failed", snapshot_id=snapshot_id, error=str(e))

    # ---------------------------------------------------------------
    # Primitives
    # ---------------------------------------------------------------

    async def wallet_profile(
        self, input: WalletProfileInput, snapshot_id: str
    ) -> WalletProfileOutput:
        # Round-trip through dict on the way IN: datamodel-codegen
        # emits a fresh `WalletProfileInput` class inside each file
        # that references it (e.g. `WalletProfileRequest.py` defines
        # its own), and pydantic strict-checks by class identity. We
        # pass dicts to bypass that. Schema parity is preserved
        # because both classes derive from the same Rust source.
        body = WalletProfileRequest.model_validate(
            {"input": input.model_dump(), "snapshot_id": snapshot_id}
        ).model_dump()
        resp = await self._client.post("/primitive/wallet_profile", json=body)
        if resp.status_code >= 400:
            self._raise_from_error(resp)
        envelope = PrimitiveResponse.model_validate(resp.json())
        return WalletProfileOutput.model_validate(envelope.value)

    async def community_summary(
        self, input: CommunitySummaryInput, snapshot_id: str
    ) -> CommunitySummaryOutput:
        body = CommunitySummaryRequest.model_validate(
            {"input": input.model_dump(), "snapshot_id": snapshot_id}
        ).model_dump()
        resp = await self._client.post("/primitive/community_summary", json=body)
        if resp.status_code >= 400:
            self._raise_from_error(resp)
        envelope = PrimitiveResponse.model_validate(resp.json())
        return CommunitySummaryOutput.model_validate(envelope.value)

    # ---------------------------------------------------------------
    # Internals
    # ---------------------------------------------------------------

    @staticmethod
    def _raise_from_error(resp: httpx.Response) -> None:
        try:
            payload = resp.json()
            kind = str(payload.get("kind", "internal"))
            message = str(payload.get("error", resp.text))
        except Exception:
            kind = "internal"
            message = resp.text
        log.warning(
            "primitive_call_failed",
            status=resp.status_code,
            kind=kind,
            message=message,
        )
        raise PrimitiveError(kind=kind, message=message, status_code=resp.status_code)
